# Generated by Django 5.2.11 on 2026-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_public_prices', models.BooleanField(default=False, help_text='Si está activado, los visitantes pueden ver precios sin iniciar sesión', verbose_name='Mostrar precios en catálogo público')),
                ('public_prices_message', models.CharField(default='Iniciá sesión o solicitá una cuenta para ver precios', max_length=255, verbose_name='Mensaje cuando precios están ocultos')),
                ('company_name', models.CharField(default='FLEXS', max_length=100, verbose_name='Nombre de la empresa')),
                ('company_email', models.EmailField(default='ventas@flexs.com.ar', max_length=254, verbose_name='Email de contacto')),
                ('company_phone', models.CharField(default='+54 011 5177-9690', max_length=50, verbose_name='Teléfono principal')),
                ('company_phone_2', models.CharField(blank=True, default='+54 011 4755-2404', max_length=50, verbose_name='Teléfono secundario')),
                ('company_address', models.TextField(default='Indalecio Gomez 4215 (Villa Lynch) San Martin, Buenos Aires. Argentina', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
