# Generated by Django 5.2.11 on 2026-02-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuracion del Sitio', 'verbose_name_plural': 'Configuracion del Sitio'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_primary_category_for_multicategory',
            field=models.BooleanField(default=False, help_text='Si esta activo, al vincular un producto a multiples categorias se exige definir categoria principal.', verbose_name='Exigir categoria principal en multi-categoria'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(default='Indalecio Gomez 4215 (Villa Lynch) San Martin, Buenos Aires. Argentina', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(default='+54 011 5177-9690', max_length=50, verbose_name='Telefono principal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone_2',
            field=models.CharField(blank=True, default='+54 011 4755-2404', max_length=50, verbose_name='Telefono secundario'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='public_prices_message',
            field=models.CharField(default='Inicia sesion o solicita una cuenta para ver precios', max_length=255, verbose_name='Mensaje cuando precios estan ocultos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_public_prices',
            field=models.BooleanField(default=False, help_text='Si esta activado, los visitantes pueden ver precios sin iniciar sesion', verbose_name='Mostrar precios en catalogo publico'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_admina_created_13548d_idx'), models.Index(fields=['action'], name='core_admina_action_0ed87f_idx'), models.Index(fields=['target_type'], name='core_admina_target__22f780_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('category_view', 'Category View'), ('filter', 'Filter')], max_length=20)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('category_slug', models.CharField(blank=True, max_length=120)),
                ('results_count', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_catalo_event_t_a2c14b_idx'), models.Index(fields=['category_slug'], name='core_catalo_categor_8bc856_idx'), models.Index(fields=['query'], name='core_catalo_query_529f4b_idx'), models.Index(fields=['results_count'], name='core_catalo_results_63d473_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('dry_run', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('rolled_back', 'Rollback aplicado')], default='processing', max_length=20)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_refs', models.JSONField(blank=True, default=list)),
                ('rollback_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_type', 'created_at'], name='core_import_import__944df4_idx'), models.Index(fields=['status'], name='core_import_status_2bf12b_idx')],
            },
        ),
    ]
