# Generated by Django 5.2.11 on 2026-02-26 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_cost_product_catalog_pro_cost_00f690_idx'),
        ('core', '0003_alter_sitesettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogExcelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_excel_templates_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_excel_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla Excel de Catalogo',
                'verbose_name_plural': 'Plantillas Excel de Catalogo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogExcelTemplateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre hoja')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('include_header', models.BooleanField(default=True, verbose_name='Incluir encabezado')),
                ('only_active_products', models.BooleanField(default=True, verbose_name='Solo productos activos')),
                ('only_catalog_visible', models.BooleanField(default=False, verbose_name='Solo visibles en catalogo')),
                ('include_descendant_categories', models.BooleanField(default=True, verbose_name='Incluir subcategorias')),
                ('search_query', models.CharField(blank=True, max_length=120, verbose_name='Busqueda interna')),
                ('max_rows', models.PositiveIntegerField(blank=True, help_text='Opcional. Dejar vacio para exportar todo.', null=True, verbose_name='Limite de filas')),
                ('sort_by', models.CharField(choices=[('name_asc', 'Nombre A-Z'), ('name_desc', 'Nombre Z-A'), ('sku_asc', 'SKU A-Z'), ('sku_desc', 'SKU Z-A'), ('updated_desc', 'Mas recientes'), ('price_desc', 'Precio mayor a menor'), ('price_asc', 'Precio menor a mayor')], default='name_asc', max_length=30, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='catalog_excel_template_sheets', to='catalog.category', verbose_name='Categorias')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='catalog_excel_template_sheets', to='catalog.supplier', verbose_name='Proveedores')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='core.catalogexceltemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Hoja de plantilla Excel',
                'verbose_name_plural': 'Hojas de plantilla Excel',
                'ordering': ['template_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogExcelTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('sku', 'SKU'), ('name', 'Nombre'), ('description', 'Descripcion'), ('supplier', 'Proveedor'), ('supplier_normalized', 'Proveedor normalizado'), ('price', 'Precio'), ('cost', 'Costo'), ('stock', 'Stock'), ('is_active', 'Producto activo'), ('is_visible_in_catalog', 'Visible en catalogo'), ('primary_category', 'Categoria principal'), ('categories', 'Categorias vinculadas'), ('filter_1', 'Filtro 1'), ('filter_2', 'Filtro 2'), ('filter_3', 'Filtro 3'), ('filter_4', 'Filtro 4'), ('filter_5', 'Filtro 5'), ('created_at', 'Creado'), ('updated_at', 'Actualizado'), ('attributes_json', 'Atributos JSON')], max_length=40, verbose_name='Campo')),
                ('header', models.CharField(blank=True, help_text='Opcional. Si se deja vacio, se usa el nombre por defecto del campo.', max_length=120, verbose_name='Encabezado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.catalogexceltemplatesheet', verbose_name='Hoja')),
            ],
            options={
                'verbose_name': 'Columna de plantilla Excel',
                'verbose_name_plural': 'Columnas de plantilla Excel',
                'ordering': ['sheet_id', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplate',
            index=models.Index(fields=['slug'], name='core_catalo_slug_acd736_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplate',
            index=models.Index(fields=['is_active'], name='core_catalo_is_acti_2e37d6_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplate',
            index=models.Index(fields=['created_at'], name='core_catalo_created_f48a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatesheet',
            index=models.Index(fields=['template', 'order'], name='core_catalo_templat_0dfc80_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatesheet',
            index=models.Index(fields=['only_active_products'], name='core_catalo_only_ac_86e7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatesheet',
            index=models.Index(fields=['only_catalog_visible'], name='core_catalo_only_ca_355e0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogexceltemplatesheet',
            unique_together={('template', 'name')},
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatecolumn',
            index=models.Index(fields=['sheet', 'order'], name='core_catalo_sheet_i_5f6d51_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatecolumn',
            index=models.Index(fields=['key'], name='core_catalo_key_93e9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogexceltemplatecolumn',
            index=models.Index(fields=['is_active'], name='core_catalo_is_acti_d65733_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogexceltemplatecolumn',
            unique_together={('sheet', 'key')},
        ),
    ]
