# Generated by Django 5.2.10 on 2026-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_default_catalog_excel_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='client_download_label',
            field=models.CharField(blank=True, default='Descargar catalogo Excel', help_text='Texto del boton que vera el cliente para descargar esta plantilla.', max_length=120, verbose_name='Texto boton cliente'),
        ),
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='is_client_download_enabled',
            field=models.BooleanField(default=False, help_text='Si esta activo, esta plantilla se publica para descarga en cuentas de cliente.', verbose_name='Disponible para clientes'),
        ),
    ]
