# Generated by Django 5.2.10 on 2026-03-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogexceltemplate_client_download_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Razon social')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('cuit', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_compan_slug_9ea5c6_idx'), models.Index(fields=['is_active'], name='core_compan_is_acti_f26725_idx')],
            },
        ),
        migrations.AddField(
            model_name='importexecution',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_executions', to='core.company', verbose_name='Empresa'),
        ),
    ]
