# Generated by Django 5.2.11 on 2026-03-09 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clientcompany_clientpayment_company_and_more'),
        ('core', '0008_backfill_companies'),
        ('orders', '0010_order_billing_company_order_billing_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('COT', 'Cotizacion'), ('PED', 'Pedido'), ('REM', 'Remito'), ('REC', 'Recibo'), ('AJU', 'Ajuste')], max_length=3, verbose_name='Tipo')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Siguiente numero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_series', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serie de Documento',
                'verbose_name_plural': 'Series de Documentos',
                'indexes': [models.Index(fields=['company', 'doc_type'], name='core_docume_company_a81d90_idx')],
                'unique_together': {('company', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(help_text='Clave idempotente para evitar duplicados.', max_length=120, unique=True, verbose_name='Clave de origen')),
                ('doc_type', models.CharField(choices=[('COT', 'Cotizacion'), ('PED', 'Pedido'), ('REM', 'Remito'), ('REC', 'Recibo'), ('AJU', 'Ajuste')], max_length=3, verbose_name='Tipo')),
                ('number', models.PositiveIntegerField(verbose_name='Numero')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha emision')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Anulado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha anulacion')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo anulacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.clientcompany', verbose_name='Cliente empresa')),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.clientprofile', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.order', verbose_name='Pedido')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.clientpayment', verbose_name='Pago')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.clienttransaction', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Documento Interno',
                'verbose_name_plural': 'Documentos Internos',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['company', 'doc_type', 'number'], name='core_intern_company_3c614a_idx'), models.Index(fields=['company', 'issued_at'], name='core_intern_company_c8bb61_idx'), models.Index(fields=['doc_type', 'issued_at'], name='core_intern_doc_typ_39d3a3_idx')],
                'unique_together': {('company', 'doc_type', 'number')},
            },
        ),
    ]
