# Generated by Django 5.2.10 on 2026-03-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('core', '0009_documentseries_internaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_companies', to='catalog.pricelist', verbose_name='Lista base'),
        ),
    ]
