# Generated by Django 5.2.10 on 2026-03-10 11:30

from django.db import migrations


def seed_company_price_lists(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    PriceList = apps.get_model("catalog", "PriceList")
    PriceListItem = apps.get_model("catalog", "PriceListItem")
    Product = apps.get_model("catalog", "Product")

    companies = list(Company.objects.all())
    if not companies:
        return

    for company in companies:
        base_name = f"{company.name} Base"
        price_list, created = PriceList.objects.get_or_create(
            company_id=company.id,
            slug="base",
            defaults={
                "name": base_name,
                "is_active": True,
            },
        )
        if not price_list.name:
            price_list.name = base_name
            price_list.save(update_fields=["name"])

        if not company.default_price_list_id:
            company.default_price_list_id = price_list.id
            company.save(update_fields=["default_price_list"])

        existing_ids = set(
            PriceListItem.objects.filter(price_list_id=price_list.id).values_list("product_id", flat=True)
        )
        batch = []
        for product in Product.objects.only("id", "price").iterator(chunk_size=1000):
            if product.id in existing_ids:
                continue
            batch.append(
                PriceListItem(
                    price_list_id=price_list.id,
                    product_id=product.id,
                    price=product.price,
                )
            )
            if len(batch) >= 1000:
                PriceListItem.objects.bulk_create(batch, batch_size=1000)
                batch = []
        if batch:
            PriceListItem.objects.bulk_create(batch, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_pricelist_pricelistitem_and_more"),
        ("core", "0010_company_default_price_list"),
    ]

    operations = [
        migrations.RunPython(seed_company_price_lists, migrations.RunPython.noop),
    ]
