# Generated by Django 5.2.10 on 2026-03-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_company_price_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio fiscal'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localidad fiscal'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_province',
            field=models.CharField(blank=True, max_length=120, verbose_name='Provincia fiscal'),
        ),
        migrations.AddField(
            model_name='company',
            name='point_of_sale_default',
            field=models.CharField(blank=True, max_length=10, verbose_name='Punto de venta (default)'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_condition',
            field=models.CharField(blank=True, choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final')], max_length=50, verbose_name='Condicion fiscal'),
        ),
        migrations.CreateModel(
            name='FiscalDocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sale', models.CharField(max_length=6, verbose_name='Punto de venta')),
                ('doc_type', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B')], max_length=3, verbose_name='Tipo')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Siguiente numero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_series', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serie Fiscal',
                'verbose_name_plural': 'Series Fiscales',
                'indexes': [models.Index(fields=['company', 'point_of_sale', 'doc_type'], name='core_fiscal_company_bc7022_idx')],
                'unique_together': {('company', 'point_of_sale', 'doc_type')},
            },
        ),
    ]
