# Generated by Django 5.2.10 on 2026-03-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalize_point_of_sale(raw_value):
    value = str(raw_value or "").strip()
    if not value:
        return "1"
    return value[:6]


def backfill_fiscal_points_of_sale(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    FiscalPointOfSale = apps.get_model("core", "FiscalPointOfSale")
    FiscalDocumentSeries = apps.get_model("core", "FiscalDocumentSeries")

    default_pos_by_company = {}

    for company in Company.objects.all().iterator():
        default_number = _normalize_point_of_sale(getattr(company, "point_of_sale_default", ""))
        point_of_sale, created = FiscalPointOfSale.objects.get_or_create(
            company_id=company.id,
            number=default_number,
            defaults={
                "name": f"PV {default_number}",
                "is_active": True,
                "environment": "homologation",
                "is_default": True,
                "notes": "",
            },
        )
        update_fields = []
        if not point_of_sale.is_default:
            point_of_sale.is_default = True
            update_fields.append("is_default")
        if not point_of_sale.name:
            point_of_sale.name = f"PV {default_number}"
            update_fields.append("name")
        if update_fields:
            point_of_sale.save(update_fields=update_fields + ["updated_at"])

        FiscalPointOfSale.objects.filter(
            company_id=company.id,
            is_default=True,
        ).exclude(pk=point_of_sale.pk).update(is_default=False)

        default_pos_by_company[company.id] = point_of_sale

    for series in FiscalDocumentSeries.objects.select_related("company").all().iterator():
        company = series.company
        point_of_sale_number = _normalize_point_of_sale(series.point_of_sale)
        point_of_sale, _ = FiscalPointOfSale.objects.get_or_create(
            company_id=company.id,
            number=point_of_sale_number,
            defaults={
                "name": f"PV {point_of_sale_number}",
                "is_active": True,
                "environment": "homologation",
                "is_default": False,
                "notes": "",
            },
        )
        changed = False
        if series.point_of_sale_ref_id != point_of_sale.id:
            series.point_of_sale_ref_id = point_of_sale.id
            changed = True
        if series.point_of_sale != point_of_sale_number:
            series.point_of_sale = point_of_sale_number
            changed = True
        if changed:
            series.save(update_fields=["point_of_sale_ref", "point_of_sale"])

    for company in Company.objects.all().only("id").iterator():
        if FiscalPointOfSale.objects.filter(company_id=company.id, is_default=True).exists():
            continue
        default_pos = default_pos_by_company.get(company.id)
        if default_pos:
            FiscalPointOfSale.objects.filter(pk=default_pos.pk).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_clienttransaction_billing_company_state'),
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('core', '0012_company_fiscal_address_company_fiscal_city_and_more'),
        ('orders', '0012_order_external_id_order_external_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='Clave de origen')),
                ('doc_type', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B')], max_length=3, verbose_name='Tipo fiscal')),
                ('issue_mode', models.CharField(choices=[('arca_wsfe', 'ARCA WSFE'), ('manual', 'Manual'), ('external_saas', 'Externo SaaS')], default='arca_wsfe', max_length=20, verbose_name='Modo de emision')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero fiscal')),
                ('status', models.CharField(choices=[('ready_to_issue', 'Listo para emitir'), ('submitting', 'Enviando'), ('authorized', 'Autorizado'), ('pending_retry', 'Pendiente reintento'), ('rejected', 'Rechazado'), ('voided', 'Anulado'), ('external_recorded', 'Registrado externo')], db_index=True, default='ready_to_issue', max_length=24, verbose_name='Estado fiscal')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emision')),
                ('cae', models.CharField(blank=True, max_length=40, verbose_name='CAE')),
                ('cae_due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('subtotal_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal neto')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('currency', models.CharField(default='ARS', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='Tipo de cambio')),
                ('external_system', models.CharField(blank=True, default='', max_length=20, verbose_name='Sistema externo')),
                ('external_id', models.CharField(blank=True, default='', max_length=80, verbose_name='ID externo')),
                ('external_number', models.CharField(blank=True, default='', max_length=80, verbose_name='Numero externo')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Response payload')),
                ('error_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Codigo error')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje error')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo intento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscales',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='Linea')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Cantidad')),
                ('unit_price_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Unitario neto')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto descuento')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Neto')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alicuota IVA (%)')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Documento Fiscal',
                'verbose_name_plural': 'Items de Documentos Fiscales',
                'ordering': ['fiscal_document_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='FiscalEmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Response payload')),
                ('result_status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('error', 'Con error')], default='pending', max_length=20, verbose_name='Resultado')),
                ('error_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Codigo error')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de Emision Fiscal',
                'verbose_name_plural': 'Intentos de Emision Fiscal',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='Punto de venta')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('environment', models.CharField(choices=[('homologation', 'Homologacion'), ('production', 'Produccion')], default='homologation', max_length=20, verbose_name='Entorno')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punto de venta fiscal',
                'verbose_name_plural': 'Puntos de venta fiscales',
                'ordering': ['company_id', 'number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocumentseries',
            name='core_fiscal_company_bc7022_idx',
        ),
        migrations.AlterField(
            model_name='fiscaldocumentseries',
            name='point_of_sale',
            field=models.CharField(blank=True, help_text='Campo legacy temporal. Usar punto_de_venta (FK).', max_length=6, verbose_name='Punto de venta'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='client_company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='accounts.clientcompany', verbose_name='Cliente empresa'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='accounts.clientprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='internal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='core.internaldocument', verbose_name='Documento interno'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='core.fiscaldocument', verbose_name='Documento relacionado'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentitem',
            name='fiscal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_document_items', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='fiscal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_attempts', to='core.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_emission_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por'),
        ),
        migrations.AddField(
            model_name='fiscalpointofsale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_points_of_sale', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='point_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='core.fiscalpointofsale', verbose_name='Punto de venta fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscaldocumentseries',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='point_of_sale_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_series', to='core.fiscalpointofsale', verbose_name='Punto de venta'),
        ),
        migrations.RunPython(backfill_fiscal_points_of_sale, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='fiscaldocumentseries',
            unique_together={('point_of_sale_ref', 'doc_type')},
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentseries',
            index=models.Index(fields=['point_of_sale_ref', 'doc_type'], name='core_fiscal_point_o_43ac59_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['fiscal_document', 'line_number'], name='core_fiscal_fiscal__f28483_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['product'], name='core_fiscal_product_abaf68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscaldocumentitem',
            unique_together={('fiscal_document', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['fiscal_document', 'created_at'], name='core_fiscal_fiscal__71c26b_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['result_status', 'created_at'], name='core_fiscal_result__9f667f_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalpointofsale',
            index=models.Index(fields=['company', 'is_active'], name='core_fiscal_company_9599cb_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalpointofsale',
            index=models.Index(fields=['company', 'is_default'], name='core_fiscal_company_4504ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalpointofsale',
            unique_together={('company', 'number')},
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['company', 'status', 'created_at'], name='core_fiscal_company_e1f1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['company', 'doc_type', 'created_at'], name='core_fiscal_company_9a0879_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['point_of_sale', 'doc_type', 'number'], name='core_fiscal_point_o_79510f_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['external_system', 'external_id'], name='core_fiscal_externa_764e0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'point_of_sale', 'doc_type', 'number'), name='uniq_fiscal_doc_company_pos_type_number'),
        ),
    ]
