# Generated by Django 5.2.11 on 2026-03-12 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('core', '0013_fiscaldocument_fiscaldocumentitem_and_more'),
        ('orders', '0012_order_external_id_order_external_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='Codigo')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('letter', models.CharField(blank=True, max_length=4, verbose_name='Letra')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Ultimo numero')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('document_behavior', models.CharField(choices=[('Factura', 'Factura'), ('NotaCredito', 'Nota de Credito'), ('NotaDebito', 'Nota de Debito'), ('Recibo', 'Recibo'), ('Remito', 'Remito'), ('Pedido', 'Pedido'), ('Presupuesto', 'Presupuesto'), ('Cotizacion', 'Cotizacion')], max_length=24, verbose_name='Tipo de comprobante')),
                ('generate_stock_movement', models.BooleanField(default=False, verbose_name='Genera movimiento de stock')),
                ('generate_account_movement', models.BooleanField(default=False, verbose_name='Genera movimiento de cuenta')),
                ('group_equal_products', models.BooleanField(default=True, verbose_name='Agrupa productos iguales')),
                ('prioritize_default_warehouse', models.BooleanField(default=True, verbose_name='Priorizar deposito predeterminado')),
                ('billing_mode', models.CharField(choices=[('INTERNAL_DOCUMENT', 'Documento interno'), ('ELECTRONIC_AFIP_WSFE', 'ARCA WSFE'), ('MANUAL_FISCAL_RECEIPT', 'Comprobante fiscal manual'), ('AFIP_ONLINE_INVOICE', 'Factura online AFIP')], default='INTERNAL_DOCUMENT', max_length=32, verbose_name='Modo de facturacion')),
                ('internal_doc_type', models.CharField(blank=True, choices=[('COT', 'Cotizacion'), ('PED', 'Pedido'), ('REM', 'Remito'), ('REC', 'Recibo'), ('AJU', 'Ajuste')], max_length=3, verbose_name='Tipo interno asociado')),
                ('fiscal_doc_type', models.CharField(blank=True, choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B')], max_length=3, verbose_name='Tipo fiscal asociado')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_types', to='core.company', verbose_name='Empresa')),
                ('default_sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sales_document_types', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor predeterminado')),
                ('point_of_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_types', to='core.fiscalpointofsale', verbose_name='Punto de venta')),
            ],
            options={
                'verbose_name': 'Tipo de documento comercial',
                'verbose_name_plural': 'Tipos de documentos comerciales',
                'ordering': ['company_id', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='sales_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='core.salesdocumenttype', verbose_name='Tipo de documento comercial'),
        ),
        migrations.AddField(
            model_name='internaldocument',
            name='sales_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_documents', to='core.salesdocumenttype', verbose_name='Tipo de documento comercial'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='Codigo')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Depositos',
                'verbose_name_plural': 'Depositos',
                'ordering': ['company_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='Clave de origen')),
                ('movement_type', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Salida'), ('reserve', 'Reserva'), ('release', 'Liberacion'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.fiscaldocument', verbose_name='Documento fiscal')),
                ('internal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.internaldocument', verbose_name='Documento interno')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='Producto')),
                ('sales_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.salesdocumenttype', verbose_name='Tipo de documento comercial')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.warehouse', verbose_name='Deposito')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_types', to='core.warehouse', verbose_name='Deposito predeterminado'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_active'], name='core_wareho_company_263db9_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'code'], name='core_wareho_company_738ccb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'created_at'], name='core_stockm_company_e2403f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='core_stockm_product_ef6271_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'created_at'], name='core_stockm_warehou_164c12_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='core_stockm_movemen_de9fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocumenttype',
            index=models.Index(fields=['company', 'enabled'], name='core_salesd_company_a2effc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocumenttype',
            index=models.Index(fields=['company', 'document_behavior'], name='core_salesd_company_4f6a52_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocumenttype',
            index=models.Index(fields=['company', 'billing_mode'], name='core_salesd_company_cb55df_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesdocumenttype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_sales_document_type_company_code'),
        ),
        migrations.AddConstraint(
            model_name='salesdocumenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company', 'document_behavior'), name='uniq_default_sales_document_type_per_behavior'),
        ),
    ]
