# Generated by Django 5.2.11 on 2026-03-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sync_importexecution_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_links', to='core.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_access_links', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Acceso admin por empresa',
                'verbose_name_plural': 'Accesos admin por empresa',
                'ordering': ['user__username', 'company__name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_adminc_user_id_145878_idx'), models.Index(fields=['company', 'is_active'], name='core_adminc_company_b43d7f_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
