# Generated by Django 5.2.10 on 2026-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ensure_admincompanyaccess_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumenttype',
            name='currency_code',
            field=models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dolares (USD)'), ('EUR', 'Euros (EUR)')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='print_address',
            field=models.CharField(blank=True, max_length=180, verbose_name='Domicilio personalizado'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='print_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email personalizado'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='print_locality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localidad personalizada'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='print_phones',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telefonos personalizados'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='print_signature',
            field=models.TextField(blank=True, verbose_name='Firma personalizada'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='use_document_situation',
            field=models.BooleanField(default=False, verbose_name='Usa funcionalidad de situacion'),
        ),
    ]
