# Generated by Django 5.2.10 on 2026-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_salesdocumenttype_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocumenttype',
            name='currency_code',
        ),
    ]
