# Generated by Django 5.2.10 on 2026-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_salesdocumenttype_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumenttype',
            name='base_design',
            field=models.CharField(choices=[('default', 'Predeterminado'), ('compact', 'Compacto'), ('extended', 'Extendido')], default='default', max_length=20, verbose_name='Diseno base'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='default_sales_user_mode',
            field=models.CharField(choices=[('CURRENT_USER', 'El usuario que agrega la venta'), ('SPECIFIC_USER', 'Usuario/Vendedor especifico'), ('UNSPECIFIED', 'Sin especificar')], default='CURRENT_USER', max_length=20, verbose_name='Modo vendedor predeterminado'),
        ),
        migrations.AddField(
            model_name='salesdocumenttype',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
