# Generated by Django 5.2.10 on 2026-03-25 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_salesdocumenttype_base_design_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='email_last_error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ultimo error de email'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='email_last_recipient',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Ultimo destinatario email'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='email_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo envio por email'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proximo reintento sugerido'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de cobro'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero de intento'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duracion (ms)'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='will_retry',
            field=models.BooleanField(default=False, verbose_name='Permite reintento'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['fiscal_document', 'attempt_number'], name='core_fiscal_fiscal__acfade_idx'),
        ),
    ]
