# Generated by Django 5.2.10 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_fiscaldocument_email_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdocumenttype",
            name="default_origin_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Todos los canales"),
                    ("catalog", "Catalogo"),
                    ("admin", "Admin"),
                    ("whatsapp", "WhatsApp"),
                    ("phone", "Telefono"),
                    ("other", "Otro"),
                ],
                default="",
                max_length=20,
                verbose_name="Canal default",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="salesdocumenttype",
            name="uniq_default_sales_document_type_per_behavior",
        ),
        migrations.AddConstraint(
            model_name="salesdocumenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("company", "document_behavior", "default_origin_channel"),
                name="uniq_default_sales_document_type_per_behavior",
            ),
        ),
    ]
