# Generated by Django 5.2.10 on 2026-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_salesdocumenttype_default_origin_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscaldocument',
            name='doc_type',
            field=models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B'), ('NCC', 'Nota de Credito C'), ('NDA', 'Nota de Debito A'), ('NDB', 'Nota de Debito B'), ('NDC', 'Nota de Debito C')], max_length=3, verbose_name='Tipo fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentseries',
            name='doc_type',
            field=models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B'), ('NCC', 'Nota de Credito C'), ('NDA', 'Nota de Debito A'), ('NDB', 'Nota de Debito B'), ('NDC', 'Nota de Debito C')], max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='salesdocumenttype',
            name='fiscal_doc_type',
            field=models.CharField(blank=True, choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B'), ('NCC', 'Nota de Credito C'), ('NDA', 'Nota de Debito A'), ('NDB', 'Nota de Debito B'), ('NDC', 'Nota de Debito C')], max_length=3, verbose_name='Tipo fiscal asociado'),
        ),
    ]
