# Generated by Django 5.2.10 on 2026-05-13 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_catalogexceltemplatesheet_group_by_subcategories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima generacion'),
        ),
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='last_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_excel_templates_generated', to=settings.AUTH_USER_MODEL, verbose_name='Ultimo generador'),
        ),
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='last_generated_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Filas ultima generacion'),
        ),
        migrations.AddField(
            model_name='catalogexceltemplate',
            name='last_generated_stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='Estadisticas ultima generacion'),
        ),
    ]
