# Generated by Codex on 2026-05-15

from django.db import migrations, models


def enable_clamp_grouping_for_existing_sheets(apps, schema_editor):
    Sheet = apps.get_model("core", "CatalogExcelTemplateSheet")
    Sheet.objects.filter(name__icontains="ABRAZADER").update(special_grouping="clamp_measure")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_catalogexceltemplate_last_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogexceltemplatesheet",
            name="special_grouping",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sin agrupacion tecnica"),
                    ("clamp_measure", "Abrazaderas por medida"),
                ],
                default="",
                help_text="Opcional. Usa una salida especial para rubros tecnicos, sin modificar categorias reales.",
                max_length=30,
                verbose_name="Agrupacion tecnica",
            ),
        ),
        migrations.RunPython(enable_clamp_grouping_for_existing_sheets, migrations.RunPython.noop),
    ]
