# Generated by Django 5.2.11 on 2026-07-13 11:58

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_strict_operator_access(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Company = apps.get_model('core', 'Company')
    AdminCompanyAccess = apps.get_model('core', 'AdminCompanyAccess')
    AdminAuditLog = apps.get_model('core', 'AdminAuditLog')

    role_names = ('admin', 'ventas', 'deposito', 'facturacion')
    role_groups = {
        name: Group.objects.get_or_create(name=name)[0]
        for name in role_names
    }
    active_companies = list(Company.objects.filter(is_active=True))
    for user in User.objects.filter(is_staff=True, is_superuser=False):
        if not user.groups.filter(name__in=role_names).exists():
            user.groups.add(role_groups['admin'])
        for company in active_companies:
            AdminCompanyAccess.objects.update_or_create(
                user=user,
                company=company,
                defaults={'is_active': True},
            )

    company_ids = set(Company.objects.values_list('id', flat=True))
    for row in AdminAuditLog.objects.filter(company__isnull=True).iterator(chunk_size=1000):
        details = row.details if isinstance(row.details, dict) else {}
        raw_company_id = details.get('company_id')
        if raw_company_id is None and isinstance(details.get('after'), dict):
            raw_company_id = details['after'].get('company') or details['after'].get('company_id')
        try:
            company_id = int(raw_company_id)
        except (TypeError, ValueError):
            continue
        if company_id in company_ids:
            AdminAuditLog.objects.filter(pk=row.pk).update(company_id=company_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_catalogexceltemplatesheet_special_grouping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='core.company', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='AdminCapabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='Capacidades')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Configurado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_capability_profiles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_capability_profile', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Permisos granulares de operador',
                'verbose_name_plural': 'Permisos granulares de operadores',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('target_url', models.URLField(max_length=500, verbose_name='URL destino')),
                ('secret', models.CharField(default=core.models.generate_webhook_secret, max_length=128, verbose_name='Secreto')),
                ('events', models.JSONField(blank=True, default=list, verbose_name='Eventos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['company_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID de evento')),
                ('event_type', models.CharField(db_index=True, max_length=60, verbose_name='Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=12, verbose_name='Estado')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('response_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP')),
                ('response_excerpt', models.CharField(blank=True, max_length=500, verbose_name='Respuesta')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='Ultimo error')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Proximo intento')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhookendpoint', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhooks',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['company', 'is_active'], name='core_webhoo_company_c963fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookendpoint',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='core_webhoo_status_6a0fea_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='core_webhoo_endpoin_18c786_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_id'), name='unique_webhook_event_per_endpoint'),
        ),
        migrations.RunPython(backfill_strict_operator_access, migrations.RunPython.noop),
    ]
