# Generated by Django 5.2.10 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_suppliercosthistory_product_supplier'),
        ('core', '0028_adminauditlog_company_admincapabilityprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEditorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En proceso'), ('completed', 'Completado'), ('partial', 'Completado con errores'), ('failed', 'Fallido'), ('rolled_back', 'Revertido'), ('rollback_partial', 'Reversion parcial')], default='pending', max_length=24)),
                ('request_payload', models.JSONField(default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_editor_jobs', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_editor_jobs_rolled_back', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEditorJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('rolled_back', 'Revertido'), ('rollback_conflict', 'Conflicto al revertir')], default='pending', max_length=24)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.externaleditorjob')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_editor_job_items', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='externaleditorjob',
            index=models.Index(fields=['status', 'created_at'], name='core_extern_status_b3a4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='externaleditorjob',
            index=models.Index(fields=['created_by', 'created_at'], name='core_extern_created_0e49fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaleditorjob',
            constraint=models.UniqueConstraint(fields=('created_by', 'idempotency_key'), name='core_editor_job_user_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='externaleditorjobitem',
            index=models.Index(fields=['job', 'status'], name='core_extern_job_id_fc849a_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaleditorjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'product_id_snapshot'), name='core_editor_job_item_product_uniq'),
        ),
    ]
