# Generated by Django 5.2.10 on 2026-07-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_product_allow_negative_stock_product_is_purchasable_and_more'),
        ('core', '0030_external_editor_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_stock_enabled',
            field=models.BooleanField(default=False, help_text='Activa la escritura de saldos por deposito despues de inicializar el inventario.', verbose_name='Activar stock por deposito'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_balance_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aplicado al saldo por deposito'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_balance_error',
            field=models.CharField(blank=True, max_length=255, verbose_name='Error de saldo por deposito'),
        ),
        migrations.CreateModel(
            name='ProductWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Stock actual')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Stock reservado')),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Stock minimo')),
                ('ideal', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Stock ideal')),
                ('initialized_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicializado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_balances', to='catalog.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_balances', to='core.warehouse', verbose_name='Deposito')),
            ],
            options={
                'verbose_name': 'Stock de producto por deposito',
                'verbose_name_plural': 'Stocks de productos por deposito',
                'ordering': ['warehouse__company_id', 'warehouse__name', 'product__name'],
                'indexes': [models.Index(fields=['warehouse', 'product'], name='core_produc_warehou_76dfa8_idx'), models.Index(fields=['product', 'updated_at'], name='core_produc_product_f51b3b_idx'), models.Index(fields=['warehouse', 'on_hand'], name='core_produc_warehou_5a3492_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_product_warehouse_stock'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='product_warehouse_reserved_gte_0'), models.CheckConstraint(condition=models.Q(('minimum__gte', 0)), name='product_warehouse_minimum_gte_0'), models.CheckConstraint(condition=models.Q(('ideal__gte', 0)), name='product_warehouse_ideal_gte_0'), models.CheckConstraint(condition=models.Q(('ideal__gte', models.F('minimum'))), name='product_warehouse_ideal_gte_minimum')],
            },
        ),
    ]
