# Generated by Django 5.2.10 on 2026-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitesettings_warehouse_stock_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='stock_balance_enabled',
            field=models.BooleanField(default=False, help_text='Solo debe activarse despues de inicializar y verificar los saldos de este deposito.', verbose_name='Usar saldos por deposito'),
        ),
    ]
