# Generated by Django 5.2.11 on 2026-07-29 11:29

import django.db.models.deletion
import hashlib
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def _digits(value):
    return "".join(char for char in str(value or "") if char.isdigit())


def _payload_hash(value):
    if not value:
        return ""
    canonical = json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _positive_small_integer(value):
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if 0 <= parsed <= 32767 else None


def backfill_fiscal_integrity(apps, schema_editor):
    """
    Preserve legacy fiscal evidence while introducing stable identities.

    UUID values are generated once per row before the unique constraints are
    installed. Existing snapshots are frozen exactly as they were persisted;
    the migration never rebuilds an authorized document from live client data.
    """
    from django.db.models import Count, Max

    alias = schema_editor.connection.alias
    FiscalDocument = apps.get_model("core", "FiscalDocument")
    FiscalDocumentSeries = apps.get_model("core", "FiscalDocumentSeries")
    FiscalEmissionAttempt = apps.get_model("core", "FiscalEmissionAttempt")

    series_manager = FiscalDocumentSeries.objects.using(alias)
    document_manager = FiscalDocument.objects.using(alias)
    attempt_manager = FiscalEmissionAttempt.objects.using(alias)

    for series in series_manager.select_related(
        "company",
        "point_of_sale_ref",
    ).all().iterator():
        point = series.point_of_sale_ref
        point_number = str(
            (getattr(point, "number", "") if point else "")
            or series.point_of_sale
            or ""
        )
        series_manager.filter(pk=series.pk).update(
            issuer_cuit=_digits(getattr(series.company, "cuit", "")),
            environment=str(
                (getattr(point, "environment", "") if point else "")
                or "disabled"
            ),
            point_of_sale=point_number,
        )

    for document in document_manager.select_related(
        "company",
        "point_of_sale",
    ).all().iterator():
        point = document.point_of_sale
        point_number = str(getattr(point, "number", "") or "")
        environment = str(getattr(point, "environment", "") or "disabled")
        issuer_cuit = _digits(getattr(document.company, "cuit", ""))

        series = series_manager.filter(
            point_of_sale_ref_id=document.point_of_sale_id,
            doc_type=document.doc_type,
        ).first()
        minimum_next = int(document.number or 0) + 1
        if series is None:
            series = series_manager.create(
                company_id=document.company_id,
                point_of_sale_ref_id=document.point_of_sale_id,
                point_of_sale=point_number,
                doc_type=document.doc_type,
                next_number=max(minimum_next, 1),
                issuer_cuit=issuer_cuit,
                environment=environment,
            )
        else:
            series_manager.filter(pk=series.pk).update(
                issuer_cuit=issuer_cuit,
                environment=environment,
                point_of_sale=point_number,
                next_number=max(int(series.next_number or 1), minimum_next, 1),
            )

        request_payload = (
            document.request_payload
            if isinstance(document.request_payload, dict)
            else {}
        )
        snapshot = request_payload.get("snapshot")
        if not isinstance(snapshot, dict):
            snapshot = {}
        emitter = snapshot.get("emitter") if isinstance(snapshot, dict) else {}
        client = snapshot.get("client") if isinstance(snapshot, dict) else {}
        emitter = emitter if isinstance(emitter, dict) else {}
        client = client if isinstance(client, dict) else {}

        snapshot_version = _positive_small_integer(snapshot.get("version"))
        document_manager.filter(pk=document.pk).update(
            correlation_id=uuid.uuid4(),
            idempotency_key=uuid.uuid4(),
            series_id=series.pk,
            fiscal_snapshot=snapshot,
            snapshot_hash=_payload_hash(snapshot),
            snapshot_schema_version=snapshot_version or 1,
            prepared_at=document.created_at if snapshot else None,
            payload_hash=_payload_hash(request_payload),
            issuer_cuit_snapshot=_digits(
                emitter.get("cuit") or issuer_cuit
            ),
            environment_snapshot=str(
                emitter.get("environment") or environment
            ),
            point_of_sale_number_snapshot=str(
                emitter.get("point_of_sale") or point_number
            ),
            receiver_iva_condition_id_snapshot=_positive_small_integer(
                client.get("iva_condition_arca_id")
            ),
            receiver_iva_condition_label_snapshot=str(
                client.get("iva_condition_arca_description")
                or client.get("tax_condition_label")
                or ""
            ),
            receiver_iva_condition_source_snapshot=str(
                client.get("iva_condition_source") or ""
            ),
        )

    for series in series_manager.all().iterator():
        highest_number = (
            document_manager.filter(series_id=series.pk)
            .aggregate(value=Max("number"))
            .get("value")
        )
        next_number = max(
            int(series.next_number or 1),
            int(highest_number or 0) + 1,
            1,
        )
        series_manager.filter(pk=series.pk).update(next_number=next_number)

    for attempt in attempt_manager.select_related("fiscal_document").all().iterator():
        document = attempt.fiscal_document
        was_sent = bool(
            attempt.request_payload
            or attempt.result_status != "pending"
        )
        attempt_manager.filter(pk=attempt.pk).update(
            correlation_id=uuid.uuid4(),
            operation="authorize",
            issuer_cuit=document.issuer_cuit_snapshot,
            environment=document.environment_snapshot,
            point_of_sale=document.point_of_sale_number_snapshot,
            doc_type=document.doc_type,
            attempted_number=document.number,
            request_may_have_been_sent=was_sent,
            dispatched_at=attempt.created_at if was_sent else None,
            completed_at=(
                attempt.created_at
                if attempt.result_status != "pending"
                else None
            ),
        )

    duplicate_series = list(
        series_manager.exclude(issuer_cuit="")
        .exclude(point_of_sale="")
        .values("issuer_cuit", "environment", "point_of_sale", "doc_type")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    if duplicate_series:
        raise RuntimeError(
            "Duplicate fiscal series identities require manual review before "
            f"migration: {duplicate_series}"
        )

    duplicate_numbers = list(
        document_manager.exclude(number__isnull=True)
        .exclude(issuer_cuit_snapshot="")
        .exclude(point_of_sale_number_snapshot="")
        .values(
            "environment_snapshot",
            "issuer_cuit_snapshot",
            "point_of_sale_number_snapshot",
            "doc_type",
            "number",
        )
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    if duplicate_numbers:
        raise RuntimeError(
            "Duplicate fiscal document identities require manual review before "
            f"migration: {duplicate_numbers}"
        )

    active_statuses = [
        "draft",
        "ready_to_issue",
        "submitting",
        "pending_retry",
        "uncertain",
        "recovery_pending",
        "recovered_not_found",
        "manual_review",
    ]
    duplicate_operations = list(
        document_manager.exclude(order_id__isnull=True)
        .filter(issue_mode="arca_wsfe", status__in=active_statuses)
        .values("company_id", "order_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    if duplicate_operations:
        raise RuntimeError(
            "Duplicate active ARCA operations require manual review before "
            f"migration: {duplicate_operations}"
        )

    duplicate_attempts = list(
        attempt_manager.values(
            "fiscal_document_id",
            "operation",
            "attempt_number",
        )
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    if duplicate_attempts:
        raise RuntimeError(
            "Duplicate fiscal attempt numbers require manual review before "
            f"migration: {duplicate_attempts}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_client_fiscal_identity'),
        ('core', '0032_warehouse_stock_balance_enabled'),
        ('orders', '0016_orderitem_fiscal_price_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcaReceiverIvaConditionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arca_id', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.CharField(max_length=160)),
                ('voucher_classes', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(max_length=40)),
                ('fetched_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['arca_id'],
            },
        ),
        migrations.CreateModel(
            name='ArcaVatRateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arca_id', models.PositiveSmallIntegerField(unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('source', models.CharField(max_length=40)),
                ('fetched_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='FiscalMutationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('attempted_fields', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default='model', max_length=80)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalSeriesReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('issuer_cuit', models.CharField(max_length=11)),
                ('environment', models.CharField(choices=[('disabled', 'Deshabilitado'), ('homologation', 'Homologacion'), ('production', 'Produccion')], max_length=20)),
                ('point_of_sale', models.CharField(max_length=6)),
                ('doc_type', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B'), ('NCC', 'Nota de Credito C'), ('NDA', 'Nota de Debito A'), ('NDB', 'Nota de Debito B'), ('NDC', 'Nota de Debito C')], max_length=3)),
                ('local_next_before', models.PositiveIntegerField()),
                ('local_next_after', models.PositiveIntegerField()),
                ('remote_last_authorized', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('matched', 'Coincide'), ('advanced', 'Serie local adelantada al remoto'), ('blocked', 'Serie bloqueada'), ('failed', 'Consulta fallida')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='activity_start_date',
            field=models.DateField(blank=True, help_text='Dato fiscal oficial. No se completa automaticamente.', null=True, verbose_name='Inicio de actividades'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='authorization_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de autorizacion remota'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='correlation_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='ID de correlacion'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='dispatch_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solicitud de despacho encolada'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='environment_snapshot',
            field=models.CharField(choices=[('disabled', 'Deshabilitado'), ('homologation', 'Homologacion'), ('production', 'Produccion')], default='disabled', max_length=20, verbose_name='Entorno usado'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='fiscal_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot fiscal inmutable'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Clave de idempotencia'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='issuer_cuit_snapshot',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='CUIT emisor usado'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='last_recovery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima consulta de recuperacion'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='next_recovery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proxima consulta de recuperacion'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash SHA-256 del payload fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='point_of_sale_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Punto de venta usado'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Snapshot fiscal preparado'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receiver_iva_condition_id_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Condicion IVA receptor usada (ARCA ID)'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receiver_iva_condition_label_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Condicion IVA receptor usada'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receiver_iva_condition_source_snapshot',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Fuente condicion IVA receptor'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receiver_iva_condition_validated_at_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validacion condicion IVA receptor usada'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='recovery_attempts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Consultas de recuperacion'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operacion fiscal resuelta'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='core.fiscaldocumentseries', verbose_name='Serie fiscal congelada'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='snapshot_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash SHA-256 del snapshot fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='snapshot_schema_version',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Version del snapshot fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentitem',
            name='arca_iva_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Identificador de alicuota ARCA'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentitem',
            name='tax_treatment',
            field=models.CharField(choices=[('taxed', 'Gravado'), ('exempt', 'Exento'), ('non_taxed', 'No gravado')], default='taxed', max_length=20, verbose_name='Tratamiento fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Serie bloqueada desde'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='blocked_by_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocked_fiscal_series', to='core.fiscaldocument', verbose_name='Documento que bloquea la serie'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo de bloqueo'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='environment',
            field=models.CharField(choices=[('disabled', 'Deshabilitado'), ('homologation', 'Homologacion'), ('production', 'Produccion')], db_index=True, default='disabled', max_length=20, verbose_name='Entorno fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='issuer_cuit',
            field=models.CharField(blank=True, db_index=True, max_length=11, verbose_name='CUIT emisor congelado'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima reconciliacion'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='remote_last_authorized',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ultimo autorizado remoto'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentseries',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version de concurrencia'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='attempted_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero intentado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Intento finalizado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID de correlacion'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Despacho remoto iniciado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Credito A'), ('NCB', 'Nota de Credito B'), ('NCC', 'Nota de Credito C'), ('NDA', 'Nota de Debito A'), ('NDB', 'Nota de Debito B'), ('NDC', 'Nota de Debito C')], default='', max_length=3, verbose_name='Tipo de comprobante intentado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='environment',
            field=models.CharField(choices=[('disabled', 'Deshabilitado'), ('homologation', 'Homologacion'), ('production', 'Produccion')], default='disabled', max_length=20, verbose_name='Entorno intentado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='issuer_cuit',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='CUIT emisor intentado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='operation',
            field=models.CharField(choices=[('authorize', 'Autorizar'), ('recover', 'Recuperar por consulta'), ('reconcile', 'Reconciliar serie')], default='authorize', max_length=20, verbose_name='Operacion'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hash del payload'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='point_of_sale',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Punto de venta intentado'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='request_may_have_been_sent',
            field=models.BooleanField(default=False, verbose_name='La solicitud pudo haber sido enviada'),
        ),
        migrations.RunPython(
            backfill_fiscal_integrity,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de correlacion'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Clave de idempotencia'),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='ID de correlacion'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.fiscaldocument', verbose_name='Documento relacionado'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('ready_to_issue', 'Listo para emitir'), ('submitting', 'Enviando'), ('authorized', 'Autorizado'), ('authorized_with_observations', 'Autorizado con observaciones'), ('uncertain', 'Resultado incierto'), ('recovery_pending', 'Consulta de recuperacion pendiente'), ('recovered_authorized', 'Autorizado recuperado'), ('recovered_not_found', 'No encontrado durante recuperacion'), ('manual_review', 'Revision manual'), ('pending_retry', 'Pendiente reintento (legado)'), ('rejected', 'Rechazado'), ('voided', 'Anulado'), ('external_recorded', 'Registrado externo')], db_index=True, default='draft', max_length=32, verbose_name='Estado fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentitem',
            name='fiscal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='fiscal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_attempts', to='core.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('error', 'Con error'), ('uncertain', 'Resultado incierto'), ('not_found', 'No encontrado'), ('recovered', 'Recuperado')], default='pending', max_length=20, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='fiscalpointofsale',
            name='environment',
            field=models.CharField(choices=[('disabled', 'Deshabilitado'), ('homologation', 'Homologacion'), ('production', 'Produccion')], default='disabled', max_length=20, verbose_name='Entorno'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['environment_snapshot', 'issuer_cuit_snapshot', 'point_of_sale_number_snapshot', 'doc_type'], name='core_fiscal_environ_a686f7_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['status', 'next_recovery_at'], name='core_fiscal_status_e891fd_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentseries',
            index=models.Index(fields=['issuer_cuit', 'environment', 'point_of_sale_ref', 'doc_type'], name='core_fiscal_issuer__506b35_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentseries',
            index=models.Index(fields=['blocked_at'], name='core_fiscal_blocked_7db265_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['correlation_id'], name='core_fiscal_correla_e8da95_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('issue_mode', 'arca_wsfe'), ('status__in', ('draft', 'manual_review', 'pending_retry', 'ready_to_issue', 'recovered_not_found', 'recovery_pending', 'submitting', 'uncertain'))), fields=('company', 'order'), name='uniq_active_arca_operation_per_order'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(number__isnull=False)
                    & ~models.Q(issuer_cuit_snapshot='')
                    & ~models.Q(point_of_sale_number_snapshot='')
                ),
                fields=(
                    'environment_snapshot',
                    'issuer_cuit_snapshot',
                    'point_of_sale_number_snapshot',
                    'doc_type',
                    'number',
                ),
                name='uniq_fiscal_doc_identity_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentseries',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('issuer_cuit', ''), _negated=True), models.Q(('point_of_sale', ''), _negated=True)), fields=('issuer_cuit', 'environment', 'point_of_sale', 'doc_type'), name='uniq_fiscal_series_identity'),
        ),
        migrations.AddConstraint(
            model_name='fiscalemissionattempt',
            constraint=models.UniqueConstraint(fields=('fiscal_document', 'operation', 'attempt_number'), name='uniq_fiscal_attempt_operation_number'),
        ),
        migrations.AddField(
            model_name='fiscalmutationaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_fiscal_mutations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalmutationaudit',
            name='fiscal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejected_mutations', to='core.fiscaldocument'),
        ),
        migrations.AddField(
            model_name='fiscalseriesreconciliation',
            name='fiscal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_reconciliations', to='core.fiscaldocument'),
        ),
        migrations.AddField(
            model_name='fiscalseriesreconciliation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.fiscaldocumentseries'),
        ),
        migrations.AddField(
            model_name='fiscalseriesreconciliation',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_series_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fiscalmutationaudit',
            index=models.Index(fields=['fiscal_document', 'created_at'], name='core_fiscal_fiscal__b68f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalseriesreconciliation',
            index=models.Index(fields=['series', 'created_at'], name='core_fiscal_series__d5414e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalseriesreconciliation',
            index=models.Index(fields=['issuer_cuit', 'environment', 'point_of_sale', 'doc_type'], name='core_fiscal_issuer__d5d1e8_idx'),
        ),
    ]
