# Generated by Django 5.2.10 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sales_document_operational_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_floating_enabled',
            field=models.BooleanField(default=True, help_text='Muestra el boton flotante de contacto directo en todas las paginas publicas.', verbose_name='Activar boton flotante de WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.CharField(blank=True, default='¡Hola FLEXS! Quisiera hacer una consulta comercial.', help_text='Texto con el que se abrira el chat automaticamente.', max_length=255, verbose_name='Mensaje predeterminado de WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='5491135179090', help_text='Formato internacional para enlaces wa.me (ej: 5491135179090). Si se deja vacio, toma el telefono principal.', max_length=50, verbose_name='Telefono para WhatsApp'),
        ),
    ]
