"""URL routes for API v1."""

from django.urls import path

from core.api_v1 import views

app_name = "api_v1"

urlpatterns = [
    path("health/", views.ApiHealthView.as_view(), name="health"),
    path("auth/token/", views.RateLimitedObtainAuthToken.as_view(), name="auth_token"),
    path("schema/", views.ApiSchemaView.as_view(), name="schema"),
    path("docs/", views.api_docs, name="docs"),
    path("catalog/categories/", views.ApiCategoryListView.as_view(), name="catalog_categories"),
    path("catalog/products/", views.ApiProductListView.as_view(), name="catalog_products"),
    path("editor/products/", views.ApiEditorProductListView.as_view(), name="editor_products"),
    path(
        "editor/products/selection-ids/",
        views.ApiEditorProductSelectionIdsView.as_view(),
        name="editor_product_selection_ids",
    ),
    path(
        "editor/products/<int:product_id>/",
        views.ApiEditorProductDetailView.as_view(),
        name="editor_product_detail",
    ),
    path("editor/categories/", views.ApiEditorCategoryListView.as_view(), name="editor_categories"),
    path("editor/suppliers/", views.ApiEditorSupplierListView.as_view(), name="editor_suppliers"),
    path("editor/bulk/preview/", views.ApiEditorBulkPreviewView.as_view(), name="editor_bulk_preview"),
    path("editor/bulk/", views.ApiEditorBulkView.as_view(), name="editor_bulk"),
    path("editor/workspace/", views.ApiEditorWorkspaceView.as_view(), name="editor_workspace"),
    path("editor/validation/", views.ApiEditorValidationView.as_view(), name="editor_validation"),
    path("editor/duplicates/", views.ApiEditorDuplicateView.as_view(), name="editor_duplicates"),
    path("editor/jobs/", views.ApiEditorJobListView.as_view(), name="editor_jobs"),
    path("editor/jobs/<int:job_id>/", views.ApiEditorJobDetailView.as_view(), name="editor_job_detail"),
    path(
        "editor/jobs/<int:job_id>/rollback/",
        views.ApiEditorJobRollbackView.as_view(),
        name="editor_job_rollback",
    ),
    path("editor/jobs/<int:job_id>/redo/", views.ApiEditorJobRedoView.as_view(), name="editor_job_redo"),
    path("editor/products/create/", views.ApiEditorProductCreateView.as_view(), name="editor_product_create"),
    path("editor/products/<int:product_id>/clone/", views.ApiEditorProductCloneView.as_view(), name="editor_product_clone"),
    path("editor/products/<int:product_id>/image/", views.ApiEditorProductImageView.as_view(), name="editor_product_image"),
    path("editor/products/<int:product_id>/trash/", views.ApiEditorProductTrashView.as_view(), name="editor_product_trash"),
    path("editor/import/preview/", views.ApiEditorSupplierImportPreviewView.as_view(), name="editor_import_preview"),
    path("editor/supplier-lists/", views.ApiEditorSupplierPriceListCollectionView.as_view(), name="editor_supplier_lists"),
    path("editor/supplier-lists/<int:batch_id>/", views.ApiEditorSupplierPriceListDetailView.as_view(), name="editor_supplier_list_detail"),
    path("editor/supplier-lists/<int:batch_id>/inspect/", views.ApiEditorSupplierPriceListInspectView.as_view(), name="editor_supplier_list_inspect"),
    path("editor/supplier-lists/<int:batch_id>/preview/", views.ApiEditorSupplierPriceListPreviewView.as_view(), name="editor_supplier_list_preview"),
    path("editor/supplier-lists/<int:batch_id>/decisions/", views.ApiEditorSupplierPriceListDecisionView.as_view(), name="editor_supplier_list_decisions"),
    path("editor/supplier-lists/<int:batch_id>/apply/", views.ApiEditorSupplierPriceListApplyView.as_view(), name="editor_supplier_list_apply"),
    path("editor/supplier-lists/<int:batch_id>/rollback/", views.ApiEditorSupplierPriceListRollbackView.as_view(), name="editor_supplier_list_rollback"),
    path("editor/supplier-lists/<int:batch_id>/report/", views.ApiEditorSupplierPriceListReportView.as_view(), name="editor_supplier_list_report"),
    path("editor/saved-views/", views.ApiEditorSavedViewListView.as_view(), name="editor_saved_views"),
    path("editor/saved-views/<int:saved_view_id>/", views.ApiEditorSavedViewDetailView.as_view(), name="editor_saved_view_detail"),
    path("editor/drafts/", views.ApiEditorDraftListView.as_view(), name="editor_drafts"),
    path("editor/drafts/<int:draft_id>/", views.ApiEditorDraftDetailView.as_view(), name="editor_draft_detail"),
    path("editor/drafts/<int:draft_id>/publish/", views.ApiEditorDraftPublishView.as_view(), name="editor_draft_publish"),
    # Compatibility routes consumed by the existing React editor in WEBFLEXS mode.
    path("editor/auth/login", views.ApiEditorLoginView.as_view(), name="editor_login_compat"),
    path("editor/auth/profile", views.ApiEditorProfileView.as_view(), name="editor_profile_compat"),
    path("editor/products", views.ApiEditorProductListView.as_view(), name="editor_products_compat"),
    path(
        "editor/products/selection-ids",
        views.ApiEditorProductSelectionIdsView.as_view(),
        name="editor_product_selection_ids_compat",
    ),
    path(
        "editor/products/<int:product_id>",
        views.ApiEditorProductDetailView.as_view(),
        name="editor_product_detail_compat",
    ),
    path("editor/saas/categories", views.ApiEditorCategoryListView.as_view(), name="editor_categories_compat"),
    path("editor/suppliers", views.ApiEditorSupplierListView.as_view(), name="editor_suppliers_compat"),
    path("editor/bulk/preview", views.ApiEditorBulkPreviewView.as_view(), name="editor_bulk_preview_compat"),
    path("editor/bulk", views.ApiEditorBulkView.as_view(), name="editor_bulk_compat"),
    path("editor/workspace", views.ApiEditorWorkspaceView.as_view(), name="editor_workspace_compat"),
    path("editor/validation", views.ApiEditorValidationView.as_view(), name="editor_validation_compat"),
    path("editor/duplicates", views.ApiEditorDuplicateView.as_view(), name="editor_duplicates_compat"),
    path("editor/jobs", views.ApiEditorJobListView.as_view(), name="editor_jobs_compat"),
    path("editor/jobs/<int:job_id>/rollback", views.ApiEditorJobRollbackView.as_view(), name="editor_job_rollback_compat"),
    path("editor/jobs/<int:job_id>/redo", views.ApiEditorJobRedoView.as_view(), name="editor_job_redo_compat"),
    path("editor/products/create", views.ApiEditorProductCreateView.as_view(), name="editor_product_create_compat"),
    path("editor/products/<int:product_id>/clone", views.ApiEditorProductCloneView.as_view(), name="editor_product_clone_compat"),
    path("editor/products/<int:product_id>/image", views.ApiEditorProductImageView.as_view(), name="editor_product_image_compat"),
    path("editor/products/<int:product_id>/trash", views.ApiEditorProductTrashView.as_view(), name="editor_product_trash_compat"),
    path("editor/import/preview", views.ApiEditorSupplierImportPreviewView.as_view(), name="editor_import_preview_compat"),
    path("editor/supplier-lists", views.ApiEditorSupplierPriceListCollectionView.as_view(), name="editor_supplier_lists_compat"),
    path("editor/supplier-lists/<int:batch_id>", views.ApiEditorSupplierPriceListDetailView.as_view(), name="editor_supplier_list_detail_compat"),
    path("editor/supplier-lists/<int:batch_id>/inspect", views.ApiEditorSupplierPriceListInspectView.as_view(), name="editor_supplier_list_inspect_compat"),
    path("editor/supplier-lists/<int:batch_id>/preview", views.ApiEditorSupplierPriceListPreviewView.as_view(), name="editor_supplier_list_preview_compat"),
    path("editor/supplier-lists/<int:batch_id>/decisions", views.ApiEditorSupplierPriceListDecisionView.as_view(), name="editor_supplier_list_decisions_compat"),
    path("editor/supplier-lists/<int:batch_id>/apply", views.ApiEditorSupplierPriceListApplyView.as_view(), name="editor_supplier_list_apply_compat"),
    path("editor/supplier-lists/<int:batch_id>/rollback", views.ApiEditorSupplierPriceListRollbackView.as_view(), name="editor_supplier_list_rollback_compat"),
    path("editor/supplier-lists/<int:batch_id>/report", views.ApiEditorSupplierPriceListReportView.as_view(), name="editor_supplier_list_report_compat"),
    path("editor/saved-views", views.ApiEditorSavedViewListView.as_view(), name="editor_saved_views_compat"),
    path("editor/saved-views/<int:saved_view_id>", views.ApiEditorSavedViewDetailView.as_view(), name="editor_saved_view_detail_compat"),
    path("editor/drafts", views.ApiEditorDraftListView.as_view(), name="editor_drafts_compat"),
    path("editor/drafts/<int:draft_id>", views.ApiEditorDraftDetailView.as_view(), name="editor_draft_detail_compat"),
    path("editor/drafts/<int:draft_id>/publish", views.ApiEditorDraftPublishView.as_view(), name="editor_draft_publish_compat"),
    path("clients/", views.ApiClientListView.as_view(), name="clients"),
    path("clients/me/", views.ApiMyClientProfileView.as_view(), name="clients_me"),
    path("orders/", views.ApiOrderListView.as_view(), name="orders"),
    path("orders/queue/", views.ApiOrderQueueView.as_view(), name="orders_queue"),
    path("orders/<int:order_id>/workflow/", views.ApiOrderWorkflowView.as_view(), name="orders_workflow"),
    path("webhooks/", views.ApiWebhookEndpointListCreateView.as_view(), name="webhooks"),
    path("webhooks/<int:endpoint_id>/", views.ApiWebhookEndpointDetailView.as_view(), name="webhook_detail"),
    path("webhooks/<int:endpoint_id>/deliveries/", views.ApiWebhookDeliveryListView.as_view(), name="webhook_deliveries"),
]
