# Generated by Django 5.2.11 on 2026-02-04 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa/Razón Social')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de Contacto')),
                ('cuit_dni', models.CharField(blank=True, max_length=20, verbose_name='CUIT/DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('address', models.TextField(blank=True, verbose_name='Domicilio')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_request', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creado')),
            ],
            options={
                'verbose_name': 'Solicitud de Cuenta',
                'verbose_name_plural': 'Solicitudes de Cuenta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa/Razón Social')),
                ('cuit_dni', models.CharField(blank=True, max_length=20, verbose_name='CUIT/DNI')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('address', models.TextField(blank=True, verbose_name='Domicilio')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Teléfonos')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (ej: 10.00 para 10%)', max_digits=5, verbose_name='Descuento (%)')),
                ('iva_condition', models.CharField(blank=True, choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final')], max_length=50, verbose_name='Condición IVA')),
                ('client_type', models.CharField(blank=True, choices=[('taller', 'Taller'), ('distribuidora', 'Distribuidora'), ('flota', 'Flota'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Cliente')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Cuenta aprobada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
                'ordering': ['company_name'],
            },
        ),
    ]
