# Generated by Django 5.2.10 on 2026-02-19 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de credito'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo cuenta corriente'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_credit_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloquear compras por credito'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Plazo de pago (dias)'),
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('invoice', 'Factura'), ('payment', 'Pago'), ('adjustment', 'Ajuste'), ('order', 'Pedido')], db_index=True, default='adjustment', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('void', 'Anulado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Haber')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_movements', to='accounts.clientprofile', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta',
                'verbose_name_plural': 'Movimientos de Cuenta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='accounts_ac_client__7696c7_idx'), models.Index(fields=['movement_type', 'status'], name='accounts_ac_movemen_8ea7b2_idx'), models.Index(fields=['due_date'], name='accounts_ac_due_dat_586179_idx')],
            },
        ),
    ]
