# Generated by Django 5.2.10 on 2026-02-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_credit_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_credit_blocked',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='payment_terms_days',
        ),
        migrations.DeleteModel(
            name='AccountMovement',
        ),
    ]
