# Generated by Django 5.2.10 on 2026-02-20 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_clientprofile_credit_limit_and_more'),
        ('orders', '0003_remove_invoiceitem_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('method', models.CharField(choices=[('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], default='transfer', max_length=20, verbose_name='Medio de pago')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Anulado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulacion')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo anulacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.clientprofile', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='Pedido asociado')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['client_profile', 'paid_at'], name='accounts_cl_client__20722f_idx'), models.Index(fields=['order', 'paid_at'], name='accounts_cl_order_i_4142ca_idx'), models.Index(fields=['is_cancelled'], name='accounts_cl_is_canc_cadfb4_idx')],
            },
        ),
    ]
