# Generated by Django 5.2.10 on 2026-02-25 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientpayment'),
        ('orders', '0007_order_orders_orde_status_25e057_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order_charge', 'Cargo por pedido'), ('payment', 'Pago'), ('adjustment', 'Ajuste manual')], max_length=24, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positivo suma deuda; negativo reduce deuda.', max_digits=12, verbose_name='Monto (+/-)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('source_key', models.CharField(db_index=True, help_text='Clave idempotente para evitar duplicados.', max_length=120, unique=True, verbose_name='Clave de origen')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha operativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta Corriente',
                'verbose_name_plural': 'Movimientos de Cuenta Corriente',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['client_profile', 'is_cancelled', 'paid_at'], name='accounts_cl_client__d37d3e_idx'),
        ),
        migrations.AddField(
            model_name='clienttransaction',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.clientprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='clienttransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
        migrations.AddField(
            model_name='clienttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_transactions', to='orders.order', verbose_name='Pedido asociado'),
        ),
        migrations.AddField(
            model_name='clienttransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='accounts.clientpayment', verbose_name='Pago asociado'),
        ),
        migrations.AddIndex(
            model_name='clienttransaction',
            index=models.Index(fields=['client_profile', 'occurred_at'], name='accounts_cl_client__34a49c_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttransaction',
            index=models.Index(fields=['transaction_type', 'occurred_at'], name='accounts_cl_transac_e3dd25_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttransaction',
            index=models.Index(fields=['order'], name='accounts_cl_order_i_317894_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttransaction',
            index=models.Index(fields=['payment'], name='accounts_cl_payment_dbea3d_idx'),
        ),
    ]
