# Generated by ChatGPT on 2026-02-25
from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def backfill_client_transactions(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    ClientPayment = apps.get_model("accounts", "ClientPayment")
    ClientTransaction = apps.get_model("accounts", "ClientTransaction")
    Order = apps.get_model("orders", "Order")

    billable_statuses = {"confirmed", "preparing", "shipped", "delivered"}

    profile_by_user_id = {
        user_id: profile_id
        for user_id, profile_id in ClientProfile.objects.exclude(user_id__isnull=True).values_list("user_id", "id")
    }

    now = timezone.now()
    for order in Order.objects.exclude(user_id__isnull=True).iterator():
        client_profile_id = profile_by_user_id.get(order.user_id)
        if not client_profile_id:
            continue
        amount = Decimal(str(order.total or "0.00")) if order.status in billable_statuses else Decimal("0.00")
        source_key = f"order:{order.pk}:charge"
        ClientTransaction.objects.update_or_create(
            source_key=source_key,
            defaults={
                "client_profile_id": client_profile_id,
                "order_id": order.pk,
                "payment_id": None,
                "transaction_type": "order_charge",
                "amount": amount,
                "description": f"Cargo pedido #{order.pk}",
                "occurred_at": getattr(order, "status_updated_at", None) or now,
                "created_by_id": None,
            },
        )

    for payment in ClientPayment.objects.exclude(client_profile_id__isnull=True).iterator():
        amount = Decimal("0.00")
        if not payment.is_cancelled:
            amount = Decimal(str(payment.amount or "0.00")) * Decimal("-1")
        source_key = f"payment:{payment.pk}:applied"
        ClientTransaction.objects.update_or_create(
            source_key=source_key,
            defaults={
                "client_profile_id": payment.client_profile_id,
                "order_id": payment.order_id,
                "payment_id": payment.pk,
                "transaction_type": "payment",
                "amount": amount,
                "description": f"Pago #{payment.pk}",
                "occurred_at": getattr(payment, "paid_at", None) or now,
                "created_by_id": payment.created_by_id,
            },
        )


def noop_reverse(apps, schema_editor):
    # Keep historical ledger data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_clienttransaction_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_client_transactions, noop_reverse),
    ]

