# Generated by Django 5.2.10 on 2026-03-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_client_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('default_sale_condition', models.CharField(choices=[('cash', 'Contado'), ('account', 'Cuenta corriente')], default='cash', max_length=20, verbose_name='Condicion de venta predeterminada')),
                ('allows_account_current', models.BooleanField(default=False, verbose_name='Habilita cuenta corriente')),
                ('account_current_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de cuenta corriente')),
                ('expose_cost', models.BooleanField(default=False, help_text='Reservado para reglas internas/visuales futuras.', verbose_name='Costo')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('price_list_name', models.CharField(default='Principal', max_length=80, verbose_name='Lista de precio')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de cliente',
                'verbose_name_plural': 'Categorias de clientes',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='accounts_cl_is_acti_72e2f0_idx'), models.Index(fields=['name'], name='accounts_cl_name_2cae1f_idx')],
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='accounts.clientcategory', verbose_name='Categoria de cliente'),
        ),
    ]
