# Generated by Codex on 2026-03-04
from django.db import migrations


def seed_client_categories(apps, schema_editor):
    ClientCategory = apps.get_model("accounts", "ClientCategory")

    defaults = [
        {
            "name": "Mostrador",
            "slug": "mostrador",
            "default_sale_condition": "cash",
            "allows_account_current": False,
            "account_current_limit": "0.00",
            "expose_cost": False,
            "discount_percentage": "10.00",
            "price_list_name": "Principal",
            "sort_order": 10,
            "is_active": True,
        },
        {
            "name": "N°1",
            "slug": "n1",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "10000000.00",
            "expose_cost": False,
            "discount_percentage": "30.00",
            "price_list_name": "Principal",
            "sort_order": 20,
            "is_active": True,
        },
        {
            "name": "N°1 (40%)",
            "slug": "n1-40",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "1000000.00",
            "expose_cost": False,
            "discount_percentage": "30.00",
            "price_list_name": "Principal",
            "sort_order": 30,
            "is_active": True,
        },
        {
            "name": "N°2",
            "slug": "n2",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "8000000.00",
            "expose_cost": False,
            "discount_percentage": "25.00",
            "price_list_name": "Principal",
            "sort_order": 40,
            "is_active": True,
        },
        {
            "name": "N°2 (50%)",
            "slug": "n2-50",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "8000000.00",
            "expose_cost": False,
            "discount_percentage": "25.00",
            "price_list_name": "Principal",
            "sort_order": 50,
            "is_active": True,
        },
        {
            "name": "N°3",
            "slug": "n3",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "5000000.00",
            "expose_cost": False,
            "discount_percentage": "20.00",
            "price_list_name": "Principal",
            "sort_order": 60,
            "is_active": True,
        },
        {
            "name": "N°3 (60%)",
            "slug": "n3-60",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "1000000.00",
            "expose_cost": False,
            "discount_percentage": "20.00",
            "price_list_name": "Principal",
            "sort_order": 70,
            "is_active": True,
        },
        {
            "name": "N°4",
            "slug": "n4",
            "default_sale_condition": "account",
            "allows_account_current": True,
            "account_current_limit": "300000.00",
            "expose_cost": False,
            "discount_percentage": "15.00",
            "price_list_name": "Principal",
            "sort_order": 80,
            "is_active": True,
        },
        {
            "name": "N°4 (70%)",
            "slug": "n4-70",
            "default_sale_condition": "cash",
            "allows_account_current": True,
            "account_current_limit": "3000000.00",
            "expose_cost": False,
            "discount_percentage": "15.00",
            "price_list_name": "Principal",
            "sort_order": 90,
            "is_active": True,
        },
        {
            "name": "Precio de lista",
            "slug": "precio-de-lista",
            "default_sale_condition": "cash",
            "allows_account_current": True,
            "account_current_limit": "5000000.00",
            "expose_cost": False,
            "discount_percentage": "0.00",
            "price_list_name": "Principal",
            "sort_order": 100,
            "is_active": True,
        },
        {
            "name": "Sin especificar",
            "slug": "sin-especificar",
            "default_sale_condition": "cash",
            "allows_account_current": False,
            "account_current_limit": "0.00",
            "expose_cost": False,
            "discount_percentage": "0.00",
            "price_list_name": "Principal",
            "sort_order": 110,
            "is_active": True,
        },
    ]

    for row in defaults:
        name = row.pop("name")
        ClientCategory.objects.update_or_create(
            name=name,
            defaults=row,
        )


def unseed_client_categories(apps, schema_editor):
    ClientCategory = apps.get_model("accounts", "ClientCategory")
    names = [
        "Mostrador",
        "N°1",
        "N°1 (40%)",
        "N°2",
        "N°2 (50%)",
        "N°3",
        "N°3 (60%)",
        "N°4",
        "N°4 (70%)",
        "Precio de lista",
        "Sin especificar",
    ]
    ClientCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_clientcategory_clientprofile_client_category"),
    ]

    operations = [
        migrations.RunPython(seed_client_categories, unseed_client_categories),
    ]
