# Generated by Django 5.2.10 on 2026-03-09 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_default_client_categories'),
        ('core', '0007_company_importexecution_company'),
        ('orders', '0007_order_orders_orde_status_25e057_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente por Empresa',
                'verbose_name_plural': 'Clientes por Empresa',
            },
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_payments', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='clienttransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_transactions', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['company', 'paid_at'], name='accounts_cl_company_8bd038_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttransaction',
            index=models.Index(fields=['company', 'occurred_at'], name='accounts_cl_company_744059_idx'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='client_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_clients', to='accounts.clientcategory', verbose_name='Categoria de cliente'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='accounts.clientprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_links', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['company', 'is_active'], name='accounts_cl_company_f12c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['client_profile', 'company'], name='accounts_cl_client__2ce501_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientcompany',
            unique_together={('client_profile', 'company')},
        ),
    ]
