# Generated by Django 5.2.10 on 2026-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clientcompany_clientpayment_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategoryCompanyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla categoria por empresa',
                'verbose_name_plural': 'Reglas categoria por empresa',
            },
        ),
    ]
