# Generated by Django 5.2.10 on 2026-03-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientcategorycompanyrule'),
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('core', '0010_company_default_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_companies', to='catalog.pricelist', verbose_name='Lista de precio'),
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['company', 'price_list'], name='accounts_cl_company_56a9c0_idx'),
        ),
        migrations.AddField(
            model_name='clientcategorycompanyrule',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rules', to='accounts.clientcategory', verbose_name='Categoria de cliente'),
        ),
        migrations.AddField(
            model_name='clientcategorycompanyrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='clientcategorycompanyrule',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_company_rules', to='catalog.pricelist', verbose_name='Lista de precio'),
        ),
        migrations.AddIndex(
            model_name='clientcategorycompanyrule',
            index=models.Index(fields=['company', 'client_category'], name='accounts_cl_company_31da44_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcategorycompanyrule',
            index=models.Index(fields=['company', 'is_active'], name='accounts_cl_company_dfd65a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientcategorycompanyrule',
            unique_together={('company', 'client_category')},
        ),
    ]
