# Generated by Django 5.2.10 on 2026-03-10 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clientcompany_price_list_and_more'),
        ('core', '0011_seed_company_price_lists'),
        ('orders', '0011_orderitem_discount_percentage_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='external_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Numero externo'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='external_system',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Sistema externo'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='origin',
            field=models.CharField(choices=[('local', 'Local'), ('external', 'Externo')], default='local', max_length=12, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('failed', 'Fallido')], default='pending', max_length=12, verbose_name='Estado sync'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha sync'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['sync_status', 'paid_at'], name='accounts_cl_sync_st_f51cba_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['external_system', 'external_id'], name='accounts_cl_externa_e868c4_idx'),
        ),
    ]
