# Generated by Django 5.2.10 on 2026-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_clientpayment_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de documento'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cuit', 'CUIT'), ('cuil', 'CUIL'), ('dni', 'DNI'), ('cdi', 'CDI'), ('passport', 'Pasaporte'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio fiscal'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fiscal_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localidad fiscal'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fiscal_province',
            field=models.CharField(blank=True, max_length=120, verbose_name='Provincia fiscal'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo postal'),
        ),
    ]
