# Generated by Django 5.2.10 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_clientprofile_document_number_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="clienttransaction",
                    name="billing_company",
                    field=models.CharField(
                        default="flexs",
                        max_length=20,
                        verbose_name="Empresa facturacion",
                    ),
                ),
            ],
        ),
    ]
