# Generated by Django 5.2.10 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_ensure_clienttransaction_billing_company_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttransaction",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha cierre"),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="movement_state",
            field=models.CharField(
                choices=[("open", "Abierto"), ("closed", "Cerrado"), ("voided", "Anulado")],
                db_index=True,
                default="open",
                max_length=12,
                verbose_name="Estado operativo",
            ),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha anulacion"),
        ),
        migrations.AddIndex(
            model_name="clienttransaction",
            index=models.Index(
                fields=["client_profile", "movement_state", "occurred_at"],
                name="acct_tx_client_state_occ_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clienttransaction",
            index=models.Index(
                fields=["company", "movement_state", "occurred_at"],
                name="acct_tx_company_state_occ_idx",
            ),
        ),
    ]
