# Generated by Django 5.2.10 on 2026-07-24 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_clientfiscalreview'),
        ('core', '0032_warehouse_stock_balance_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='commercial_observation',
            field=models.TextField(blank=True, help_text='Contexto general para ventas y atencion del cliente.', verbose_name='Observacion comercial'),
        ),
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('note', models.TextField(blank=True, verbose_name='Detalle')),
                ('due_at', models.DateTimeField(verbose_name='Fecha del recordatorio')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=16, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=16, verbose_name='Estado')),
                ('completion_note', models.TextField(blank=True, verbose_name='Resultado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_client_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_tasks', to='accounts.clientprofile', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_tasks', to='core.company', verbose_name='Empresa')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_client_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Tarea comercial de cliente',
                'verbose_name_plural': 'Tareas comerciales de clientes',
                'ordering': ['status', 'due_at', '-priority', '-id'],
                'indexes': [models.Index(fields=['company', 'status', 'due_at'], name='accounts_cl_company_f78126_idx'), models.Index(fields=['assigned_to', 'status', 'due_at'], name='accounts_cl_assigne_60f7ea_idx'), models.Index(fields=['client_profile', 'status', 'due_at'], name='accounts_cl_client__a83f41_idx')],
            },
        ),
    ]
