# Generated by Django 5.2.11 on 2026-07-29 11:29

from django.db import migrations, models


def backfill_normalized_fiscal_documents(apps, schema_editor):
    """
    Freeze every unambiguous legacy fiscal document without deleting duplicates.

    Duplicate legacy identities remain NULL so the unique constraint can be
    installed safely and the existing fiscal-review workflow can resolve them
    explicitly. New/edited records are still validated by ClientProfile.save().
    """
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    candidates = {}

    for client in ClientProfile.objects.all().iterator():
        raw_value = client.document_number or client.cuit_dni or ""
        normalized = "".join(
            char for char in str(raw_value).strip() if char.isalnum()
        ).upper()
        if not normalized:
            continue
        candidates.setdefault(normalized, []).append(client.pk)

    for normalized, client_ids in candidates.items():
        if len(client_ids) != 1:
            continue
        ClientProfile.objects.filter(pk=client_ids[0]).update(
            normalized_fiscal_document=normalized,
            iva_condition_source="legacy_pending",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_clientprofile_commercial_observation_clienttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='iva_condition_arca_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Condicion IVA ARCA ID'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='iva_condition_source',
            field=models.CharField(choices=[('unknown', 'Pendiente de validar'), ('legacy_pending', 'Dato historico pendiente'), ('manual', 'Validacion manual'), ('arca', 'Parametro ARCA'), ('provider', 'Proveedor externo'), ('import', 'Importacion')], default='unknown', max_length=20, verbose_name='Fuente condicion IVA'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='iva_condition_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Condicion IVA validada'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='normalized_fiscal_document',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Documento fiscal normalizado'),
        ),
        migrations.RunPython(
            backfill_normalized_fiscal_documents,
            migrations.RunPython.noop,
        ),
    ]
