# Generated by Django 5.2.11 on 2026-02-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('filter_1', models.CharField(blank=True, max_length=100, verbose_name='Filtro 1')),
                ('filter_2', models.CharField(blank=True, max_length=100, verbose_name='Filtro 2')),
                ('filter_3', models.CharField(blank=True, max_length=100, verbose_name='Filtro 3')),
                ('filter_4', models.CharField(blank=True, max_length=100, verbose_name='Filtro 4')),
                ('filter_5', models.CharField(blank=True, max_length=100, verbose_name='Filtro 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbrazaderaSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricacion', models.CharField(blank=True, choices=[('trefilada', 'Trefilada'), ('laminada', 'Laminada')], db_index=True, max_length=20, verbose_name='Fabricación')),
                ('diametro', models.CharField(blank=True, db_index=True, help_text='Ejemplo: 1/2, 7/16, 3/4', max_length=20, verbose_name='Diámetro')),
                ('ancho', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ancho (mm)')),
                ('largo', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Largo (mm)')),
                ('tipo', models.CharField(blank=True, choices=[('plana', 'Plana'), ('curva', 'Curva'), ('semicurva', 'Semicurva'), ('s_curva', 'S/Curva')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('manual_override', models.BooleanField(default=False, help_text='Si está marcado, el parser no sobrescribirá estos datos', verbose_name='Editado manualmente')),
                ('parse_warning', models.TextField(blank=True, verbose_name='Advertencias del parser')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abrazadera_spec', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación de Abrazadera',
                'verbose_name_plural': 'Especificaciones de Abrazaderas',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent__5307be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['filter_1'], name='catalog_pro_filter__b29497_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['filter_2'], name='catalog_pro_filter__c451be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['filter_3'], name='catalog_pro_filter__4f72b6_idx'),
        ),
        migrations.AddIndex(
            model_name='abrazaderaspec',
            index=models.Index(fields=['fabricacion'], name='catalog_abr_fabrica_e97991_idx'),
        ),
        migrations.AddIndex(
            model_name='abrazaderaspec',
            index=models.Index(fields=['diametro'], name='catalog_abr_diametr_129692_idx'),
        ),
        migrations.AddIndex(
            model_name='abrazaderaspec',
            index=models.Index(fields=['ancho'], name='catalog_abr_ancho_da6a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='abrazaderaspec',
            index=models.Index(fields=['largo'], name='catalog_abr_largo_467c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='abrazaderaspec',
            index=models.Index(fields=['tipo'], name='catalog_abr_tipo_fbf5a0_idx'),
        ),
    ]
