# Generated by Django 5.2.10 on 2026-02-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Atributos'),
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Selección')], default='text', max_length=20, verbose_name='Tipo de dato')),
                ('options', models.TextField(blank=True, help_text='Opciones separadas por coma (solo para tipo Selección)', verbose_name='Opciones')),
                ('required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('regex_pattern', models.CharField(blank=True, help_text="Regex para extraer valor. Ej: 'Diámetro: (\\d+mm)'", max_length=255, null=True, verbose_name='Patrón Regex')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Atributo de Categoría',
                'verbose_name_plural': 'Atributos de Categoría',
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
