# Generated by Django 5.2.10 on 2026-02-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_attributes_categoryattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClampSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrication', models.CharField(blank=True, choices=[('TREFILADA', 'TREFILADA'), ('LAMINADA', 'LAMINADA')], max_length=20, null=True, verbose_name='Fabricación')),
                ('diameter', models.CharField(blank=True, max_length=20, null=True, verbose_name='Diámetro')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ancho (mm)')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Largo (mm)')),
                ('shape', models.CharField(blank=True, choices=[('PLANA', 'PLANA'), ('CURVA', 'CURVA'), ('SEMICURVA', 'SEMICURVA')], max_length=20, null=True, verbose_name='Forma')),
                ('parse_confidence', models.IntegerField(default=0, verbose_name='Confianza Parser (%)')),
                ('parse_warnings', models.JSONField(blank=True, default=list, verbose_name='Warnings')),
                ('manual_override', models.BooleanField(default=False, help_text='Si es True, el parser no sobrescribirá estos datos.', verbose_name='Manual Override')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clamp_specs', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación Abrazadera',
                'verbose_name_plural': 'Especificaciones Abrazaderas',
            },
        ),
        migrations.DeleteModel(
            name='AbrazaderaSpec',
        ),
    ]
