# Generated by Django 5.2.10 on 2026-02-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_clampspecs_delete_abrazaderaspec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'verbose_name': 'Atributo de categoria', 'verbose_name_plural': 'Atributos de categoria'},
        ),
        migrations.AlterModelOptions(
            name='clampspecs',
            options={'verbose_name': 'Especificacion abrazadera', 'verbose_name_plural': 'Especificaciones abrazaderas'},
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_m2m', to='catalog.category', verbose_name='Categorias vinculadas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoria padre'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='options',
            field=models.TextField(blank=True, help_text='Opciones separadas por coma (solo para tipo Seleccion)', verbose_name='Opciones'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='regex_pattern',
            field=models.CharField(blank=True, help_text="Regex para extraer valor. Ej: 'Diametro: (\\d+mm)'", max_length=255, null=True, verbose_name='Patron Regex'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('select', 'Seleccion')], default='text', max_length=20, verbose_name='Tipo de dato'),
        ),
        migrations.AlterField(
            model_name='clampspecs',
            name='diameter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diametro'),
        ),
        migrations.AlterField(
            model_name='clampspecs',
            name='fabrication',
            field=models.CharField(blank=True, choices=[('TREFILADA', 'TREFILADA'), ('LAMINADA', 'LAMINADA')], max_length=20, null=True, verbose_name='Fabricacion'),
        ),
        migrations.AlterField(
            model_name='clampspecs',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Si es True, el parser no sobrescribira estos datos.', verbose_name='Manual override'),
        ),
        migrations.AlterField(
            model_name='clampspecs',
            name='parse_confidence',
            field=models.IntegerField(default=0, verbose_name='Confianza parser (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoria principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
    ]
