# Generated by Codex on 2026-02-18
from django.db import migrations


def forwards(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Through = Product.categories.through

    rows = []
    for product_id, category_id in Product.objects.exclude(category_id__isnull=True).values_list("id", "category_id"):
        rows.append(Through(product_id=product_id, category_id=category_id))

    if rows:
        Through.objects.bulk_create(rows, ignore_conflicts=True, batch_size=2000)


def backwards(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Through = Product.categories.through

    valid_pairs = set(
        Product.objects.exclude(category_id__isnull=True).values_list("id", "category_id")
    )

    if not valid_pairs:
        Through.objects.all().delete()
        return

    for link in Through.objects.all().iterator():
        if (link.product_id, link.category_id) not in valid_pairs:
            link.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
