# Generated by Django 5.2.11 on 2026-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_backfill_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Opcional. Descripción para buscadores de esta categoría.', max_length=255, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Opcional. Título para buscadores de esta categoría.', max_length=160, verbose_name='SEO title'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='catalog_cat_order_b0952e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__e2d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='clampspecs',
            index=models.Index(fields=['fabrication'], name='catalog_cla_fabrica_4c53d9_idx'),
        ),
        migrations.AddIndex(
            model_name='clampspecs',
            index=models.Index(fields=['diameter'], name='catalog_cla_diamete_fcdaae_idx'),
        ),
        migrations.AddIndex(
            model_name='clampspecs',
            index=models.Index(fields=['width'], name='catalog_cla_width_107716_idx'),
        ),
        migrations.AddIndex(
            model_name='clampspecs',
            index=models.Index(fields=['length'], name='catalog_cla_length_40bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='clampspecs',
            index=models.Index(fields=['shape'], name='catalog_cla_shape_dd06aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='catalog_pro_updated_951dea_idx'),
        ),
    ]
