# Generated by Django 5.2.11 on 2026-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_seo_description_category_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='catalog_pro_supplie_587c74_idx'),
        ),
    ]
