# Generated by Django 5.2.11 on 2026-02-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('normalized_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_sup_name_018e39_idx'), models.Index(fields=['slug'], name='catalog_sup_slug_ca9723_idx'), models.Index(fields=['is_active'], name='catalog_sup_is_acti_4b6ba8_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier', verbose_name='Proveedor normalizado'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier_ref'], name='catalog_pro_supplie_618ab6_idx'),
        ),
    ]
