# Generated by Codex on 2026-02-18

import re
from django.db import migrations
from django.utils.text import slugify


def forward_backfill_supplier_refs(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Supplier = apps.get_model("catalog", "Supplier")

    existing = {s.normalized_name: s for s in Supplier.objects.all()}
    used_slugs = set(Supplier.objects.values_list("slug", flat=True))

    def build_unique_slug(name):
        base = slugify(name) or "proveedor"
        slug = base
        counter = 1
        while slug in used_slugs:
            slug = f"{base}-{counter}"
            counter += 1
        used_slugs.add(slug)
        return slug

    products_to_update = []
    for product in Product.objects.all().iterator():
        raw = str(product.supplier or "")
        cleaned = re.sub(r"\s+", " ", raw).strip()
        if not cleaned:
            if product.supplier_ref_id:
                product.supplier_ref_id = None
                products_to_update.append(product)
            continue

        normalized = cleaned.upper()
        supplier = existing.get(normalized)
        if supplier is None:
            supplier = Supplier.objects.create(
                name=cleaned,
                normalized_name=normalized,
                slug=build_unique_slug(cleaned),
                is_active=True,
            )
            existing[normalized] = supplier

        needs_update = False
        if product.supplier != cleaned:
            product.supplier = cleaned
            needs_update = True
        if product.supplier_ref_id != supplier.id:
            product.supplier_ref_id = supplier.id
            needs_update = True
        if needs_update:
            products_to_update.append(product)

    if products_to_update:
        Product.objects.bulk_update(products_to_update, ["supplier", "supplier_ref"])


def reverse_backfill_supplier_refs(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.update(supplier_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_supplier_product_supplier_ref_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_backfill_supplier_refs, reverse_backfill_supplier_refs),
    ]
