# Generated by Django 5.2.10 on 2026-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_backfill_supplier_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='is_recommended',
            field=models.BooleanField(default=True, help_text='Si esta activo, se sugiere completar este atributo aunque no sea obligatorio.', verbose_name='Recomendado'),
        ),
    ]
