# Generated by Django 5.2.11 on 2026-02-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_categoryattribute_is_recommended"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClampMeasureRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_name", models.CharField(blank=True, max_length=200, verbose_name="Cliente")),
                ("client_email", models.EmailField(blank=True, max_length=254, verbose_name="Email cliente")),
                ("client_phone", models.CharField(blank=True, max_length=120, verbose_name="Telefono cliente")),
                ("clamp_type", models.CharField(choices=[("trefilada", "Trefilada"), ("laminada", "Laminada")], max_length=20, verbose_name="Tipo abrazadera")),
                ("is_zincated", models.BooleanField(default=False, verbose_name="Zincado")),
                ("diameter", models.CharField(max_length=20, verbose_name="Diametro")),
                ("width_mm", models.PositiveIntegerField(verbose_name="Ancho (mm)")),
                ("length_mm", models.PositiveIntegerField(verbose_name="Largo (mm)")),
                ("profile_type", models.CharField(choices=[("PLANA", "PLANA"), ("SEMICURVA", "SEMICURVA"), ("CURVA", "CURVA")], max_length=20, verbose_name="Tipo")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Cantidad")),
                ("description", models.CharField(max_length=320, verbose_name="Descripcion generada")),
                ("generated_code", models.CharField(blank=True, max_length=80, verbose_name="Codigo sugerido")),
                ("dollar_rate", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Dolar")),
                ("steel_price_usd", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Precio acero USD")),
                ("supplier_discount_pct", models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Desc. proveedor (%)")),
                ("general_increase_pct", models.DecimalField(decimal_places=2, default=23, max_digits=6, verbose_name="Aumento gral. (%)")),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Costo base")),
                ("selected_price_list", models.CharField(choices=[("lista_1", "Lista 1"), ("lista_2", "Lista 2"), ("lista_3", "Lista 3"), ("lista_4", "Lista 4"), ("facturacion", "Facturacion")], default="lista_1", max_length=20, verbose_name="Lista seleccionada")),
                ("estimated_final_price", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Precio estimado")),
                ("exists_in_catalog", models.BooleanField(default=False, verbose_name="Existe en catalogo")),
                ("status", models.CharField(choices=[("pending", "Pendiente"), ("in_review", "En revision"), ("quoted", "Cotizada"), ("rejected", "Rechazada"), ("completed", "Completada")], default="pending", max_length=20, verbose_name="Estado")),
                ("client_note", models.TextField(blank=True, verbose_name="Nota cliente")),
                ("admin_note", models.TextField(blank=True, verbose_name="Nota admin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="Fecha procesamiento")),
                ("client_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clamp_measure_requests", to=settings.AUTH_USER_MODEL, verbose_name="Cliente usuario")),
                ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_clamp_measure_requests", to=settings.AUTH_USER_MODEL, verbose_name="Procesado por")),
            ],
            options={
                "verbose_name": "Solicitud de abrazadera a medida",
                "verbose_name_plural": "Solicitudes de abrazaderas a medida",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="catalog_cla_status_e47c6d_idx"),
                    models.Index(fields=["client_user", "created_at"], name="catalog_cla_client__cf2a46_idx"),
                    models.Index(
                        fields=["clamp_type", "diameter", "width_mm", "length_mm", "profile_type"],
                        name="catalog_cla_clamp_t_b66ac6_idx",
                    ),
                ],
            },
        ),
    ]
