# Generated by Django 5.2.11 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_clampmeasurerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="clampmeasurerequest",
            name="client_response_note",
            field=models.TextField(blank=True, verbose_name="Respuesta visible para cliente"),
        ),
        migrations.AddField(
            model_name="clampmeasurerequest",
            name="confirmed_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Precio confirmado"),
        ),
        migrations.AddField(
            model_name="clampmeasurerequest",
            name="confirmed_price_list",
            field=models.CharField(blank=True, choices=[("lista_1", "Lista 1"), ("lista_2", "Lista 2"), ("lista_3", "Lista 3"), ("lista_4", "Lista 4"), ("facturacion", "Facturacion")], max_length=20, verbose_name="Lista confirmada"),
        ),
        migrations.AddField(
            model_name="clampmeasurerequest",
            name="quoted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha precio confirmado"),
        ),
    ]
