# Generated by Django 5.2.11 on 2026-02-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_clampmeasurerequest_confirmed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clampmeasurerequest',
            name='added_to_cart_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha agregado al carrito'),
        ),
        migrations.AddField(
            model_name='clampmeasurerequest',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_clamp_requests', to='catalog.product', verbose_name='Producto vinculado'),
        ),
        migrations.AddField(
            model_name='clampmeasurerequest',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha incorporado a pedido'),
        ),
        migrations.AddField(
            model_name='clampmeasurerequest',
            name='published_to_catalog_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha publicado en catalogo'),
        ),
    ]
