# Generated by Django 5.2.11 on 2026-02-23 11:05

from django.db import migrations, models


COST_INDEX_NAME = "catalog_pro_cost_00f690_idx"


def _get_column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name})")
            return {row[1] for row in cursor.fetchall()}

        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
        return {column.name for column in description}


def add_cost_column_if_missing(apps, schema_editor):
    table_name = "catalog_product"
    columns = _get_column_names(schema_editor, table_name)
    if "cost" in columns:
        return

    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE catalog_product ADD COLUMN cost numeric(12,2) NOT NULL DEFAULT 0"
        )
    elif vendor == "sqlite":
        schema_editor.execute(
            "ALTER TABLE catalog_product ADD COLUMN cost decimal NOT NULL DEFAULT 0"
        )
    else:
        schema_editor.execute(
            "ALTER TABLE catalog_product ADD COLUMN cost decimal(12,2) NOT NULL DEFAULT 0"
        )


def add_cost_index_if_missing(apps, schema_editor):
    table_name = "catalog_product"
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
    if COST_INDEX_NAME in constraints:
        return

    schema_editor.execute(
        f"CREATE INDEX {COST_INDEX_NAME} ON {table_name} (cost)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_clampmeasurerequest_added_to_cart_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_cost_column_if_missing, migrations.RunPython.noop),
                migrations.RunPython(add_cost_index_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='cost',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo'),
                ),
                migrations.AddIndex(
                    model_name='product',
                    index=models.Index(fields=['cost'], name=COST_INDEX_NAME),
                ),
            ],
        ),
    ]
