# Generated by Django 5.2.10 on 2026-03-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_cost_product_catalog_pro_cost_00f690_idx'),
        ('core', '0007_company_importexecution_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='clampmeasurerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clamp_measure_requests', to='core.company', verbose_name='Empresa'),
        ),
    ]
