# Generated by Django 5.2.10 on 2026-03-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_clampmeasurerequest_company'),
        ('core', '0009_documentseries_internaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lista de precio',
                'verbose_name_plural': 'Listas de precios',
                'ordering': ['company_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.pricelist', verbose_name='Lista de precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Precio de lista',
                'verbose_name_plural': 'Precios de lista',
            },
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['company', 'is_active'], name='catalog_pri_company_4f5a21_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['company', 'slug'], name='catalog_pri_company_ceec39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['price_list', 'product'], name='catalog_pri_price_l_160374_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['product'], name='catalog_pri_product_08372a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'product')},
        ),
    ]
