# Generated by Django 5.2.10 on 2026-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
        migrations.AddField(
            model_name='category',
            name='public_description',
            field=models.TextField(blank=True, help_text='Texto corto opcional para el catalogo de clientes.', verbose_name='Descripcion publica'),
        ),
        migrations.AddField(
            model_name='category',
            name='public_name',
            field=models.CharField(blank=True, help_text='Nombre visible para clientes. Si queda vacio se usa el nombre interno.', max_length=120, verbose_name='Nombre publico'),
        ),
        migrations.AddField(
            model_name='category',
            name='public_order',
            field=models.IntegerField(default=0, help_text='Orden comercial para el catalogo de clientes.', verbose_name='Orden publico'),
        ),
        migrations.AddField(
            model_name='category',
            name='visible_in_catalog',
            field=models.BooleanField(default=True, help_text='Controla si esta categoria aparece y habilita visibilidad publica de productos.', verbose_name='Visible en catalogo'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['visible_in_catalog'], name='catalog_cat_visible_23cc83_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['public_order'], name='catalog_cat_public__e89cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'visible_in_catalog'], name='catalog_cat_parent__25159a_idx'),
        ),
    ]
