# Generated by Django 5.2.10 on 2026-05-08 11:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_category_product_order(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    CategoryProductOrder = apps.get_model("catalog", "CategoryProductOrder")
    through_model = Product.categories.through

    product_ids_by_category = {}
    for category_id, product_id in through_model.objects.values_list("category_id", "product_id").iterator():
        product_ids_by_category.setdefault(category_id, set()).add(product_id)

    for product_id, category_id in (
        Product.objects.exclude(category_id__isnull=True)
        .values_list("id", "category_id")
        .iterator()
    ):
        product_ids_by_category.setdefault(category_id, set()).add(product_id)

    rows = []
    for category_id, product_ids in product_ids_by_category.items():
        ordered_product_ids = list(
            Product.objects.filter(id__in=product_ids)
            .order_by("name", "sku", "id")
            .values_list("id", flat=True)
        )
        for index, product_id in enumerate(ordered_product_ids, start=1):
            rows.append(
                CategoryProductOrder(
                    category_id=category_id,
                    product_id=product_id,
                    sort_order=index * 10,
                )
            )
        if len(rows) >= 2000:
            CategoryProductOrder.objects.bulk_create(rows, ignore_conflicts=True, batch_size=2000)
            rows = []

    if rows:
        CategoryProductOrder.objects.bulk_create(rows, ignore_conflicts=True, batch_size=2000)


def reverse_backfill_category_product_order(apps, schema_editor):
    CategoryProductOrder = apps.get_model("catalog", "CategoryProductOrder")
    CategoryProductOrder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_category_is_featured_category_public_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_rows', to='catalog.category', verbose_name='Categoria')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_order_rows', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Orden de producto por categoria',
                'verbose_name_plural': 'Ordenes de productos por categoria',
                'ordering': ['category_id', 'sort_order', 'product__name', 'product_id'],
                'indexes': [models.Index(fields=['category', 'sort_order', 'product'], name='catalog_cat_categor_710614_idx'), models.Index(fields=['product', 'category'], name='catalog_cat_product_6d52e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'product'), name='uniq_category_product_order')],
            },
        ),
        migrations.RunPython(
            backfill_category_product_order,
            reverse_backfill_category_product_order,
        ),
    ]
