# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clampspecs",
            name="fabrication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TREFILADA", "TREFILADA"),
                    ("LAMINADA", "LAMINADA"),
                    ("FORJADA", "FORJADA"),
                ],
                max_length=20,
                null=True,
                verbose_name="Fabricacion",
            ),
        ),
    ]
