# Generated by Django 5.2.10 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_clampspecs_fabrication"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryproductorder",
            name="block_label",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120, verbose_name="Bloque"),
        ),
        migrations.AddField(
            model_name="categoryproductorder",
            name="block_order",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Orden de bloque"),
        ),
        migrations.AddIndex(
            model_name="categoryproductorder",
            index=models.Index(fields=["category", "block_order", "sort_order", "product"], name="catalog_cat_categor_269833_idx"),
        ),
        migrations.AlterModelOptions(
            name="categoryproductorder",
            options={
                "ordering": ["category_id", "block_order", "sort_order", "product__name", "product_id"],
                "verbose_name": "Orden de producto por categoria",
                "verbose_name_plural": "Ordenes de productos por categoria",
            },
        ),
    ]
