# Generated by Django 5.2.11 on 2026-06-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_categoryproductorder_block_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Marca')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='brands/banners/', verbose_name='Banner Comercial')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': '1. Marcas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Rubro')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/rubros/', verbose_name='Imagen Representativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='catalog.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Rubro de Marca',
                'verbose_name_plural': '2. Rubros de Marcas',
                'ordering': ['order', 'name'],
                'unique_together': {('brand', 'name'), ('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BrandSubrubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Subrubro')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/subrubros/', verbose_name='Imagen Representativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('brand_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='catalog.brandrubro', verbose_name='Rubro')),
                ('helper_categories', models.ManyToManyField(blank=True, help_text='Los productos en estas categorías se utilizarán para alimentar automáticamente este subrubro.', related_name='brand_subrubros_linked', to='catalog.category', verbose_name='Categorías Ayudantes')),
            ],
            options={
                'verbose_name': 'Subrubro de Marca',
                'verbose_name_plural': '3. Subrubros de Marcas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandSubrubroProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('brand_subrubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_rows', to='catalog.brandsubrubro', verbose_name='Subrubro de Marca')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_subrubro_orders', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Orden de producto por Subrubro de Marca',
                'verbose_name_plural': 'Orden de productos por Subrubro de Marca',
                'ordering': ['brand_subrubro_id', 'sort_order', 'product__name'],
            },
        ),
        migrations.AddField(
            model_name='brandsubrubro',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='brand_subrubros', through='catalog.BrandSubrubroProductOrder', to='catalog.product', verbose_name='Productos'),
        ),
        migrations.AddConstraint(
            model_name='brandsubrubroproductorder',
            constraint=models.UniqueConstraint(fields=('brand_subrubro', 'product'), name='uniq_brand_subrubro_product_order'),
        ),
        migrations.AlterUniqueTogether(
            name='brandsubrubro',
            unique_together={('brand_rubro', 'name'), ('brand_rubro', 'slug')},
        ),
    ]
