# Generated by Django 5.2.10 on 2026-06-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_brand_brandrubro_brandsubrubro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrubro',
            name='badge_color',
            field=models.CharField(default='orange', max_length=30, verbose_name='Color del Badge'),
        ),
        migrations.AddField(
            model_name='brandrubro',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Texto del Badge'),
        ),
        migrations.AddField(
            model_name='brandrubro',
            name='icon_emoji',
            field=models.CharField(default='📂', max_length=20, verbose_name='Emoji/Ícono'),
        ),
        migrations.CreateModel(
            name='BrandRubroProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('brand_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_rows', to='catalog.brandrubro', verbose_name='Rubro de Marca')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_rubro_orders', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Orden de producto por Rubro de Marca',
                'verbose_name_plural': 'Orden de productos por Rubro de Marca',
                'ordering': ['brand_rubro_id', 'sort_order', 'product__name'],
            },
        ),
        migrations.AddField(
            model_name='brandrubro',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='brand_rubros', through='catalog.BrandRubroProductOrder', to='catalog.product', verbose_name='Productos'),
        ),
        migrations.AddConstraint(
            model_name='brandrubroproductorder',
            constraint=models.UniqueConstraint(fields=('brand_rubro', 'product'), name='uniq_brand_rubro_product_order'),
        ),
    ]
