# Generated by Django 5.2.10 on 2026-07-14 11:01

import django.core.validators
import django.db.models.deletion
import re
from collections import defaultdict
from django.conf import settings
from django.db import migrations, models


def backfill_preferred_supplier_offers(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    ProductSupplier = apps.get_model('catalog', 'ProductSupplier')
    SupplierCostHistory = apps.get_model('catalog', 'SupplierCostHistory')
    ProductDuplicateReview = apps.get_model('catalog', 'ProductDuplicateReview')
    database = schema_editor.connection.alias
    batch_size = 1000
    pending = []

    def flush(rows):
        if not rows:
            return
        created_offers = ProductSupplier.objects.using(database).bulk_create(rows, batch_size=batch_size)
        SupplierCostHistory.objects.using(database).bulk_create(
            [
                SupplierCostHistory(
                    product_supplier=offer,
                    previous_cost=None,
                    new_cost=offer.current_cost,
                    difference_amount=0,
                    difference_percentage=None,
                    currency='ARS',
                    source='legacy_backfill',
                    reason='Linea base creada al habilitar proveedores multiples.',
                )
                for offer in created_offers
            ],
            batch_size=batch_size,
        )

    products = list(
        Product.objects.using(database)
        .filter(supplier_ref_id__isnull=False)
        .only('id', 'supplier_ref_id', 'cost', 'attributes')
    )
    code_groups = defaultdict(list)
    raw_codes = {}
    for product in products:
        attributes = product.attributes if isinstance(product.attributes, dict) else {}
        raw_code = str(
            attributes.get('Codigo proveedor')
            or attributes.get('Código proveedor')
            or attributes.get('codigo_proveedor')
            or ''
        ).strip()[:100]
        normalized_code = re.sub(r'\s+', ' ', raw_code).upper()
        if normalized_code:
            raw_codes[product.id] = (raw_code, normalized_code)
            code_groups[(product.supplier_ref_id, normalized_code)].append(product.id)

    ambiguous_product_ids = {
        product_id
        for product_ids in code_groups.values()
        if len(product_ids) > 1
        for product_id in product_ids
    }
    for product in products:
        cost = product.cost or 0
        supplier_code, normalized_code = raw_codes.get(product.id, ('', ''))
        if product.id in ambiguous_product_ids:
            supplier_code, normalized_code = '', ''
        pending.append(
            ProductSupplier(
                product_id=product.id,
                supplier_id=product.supplier_ref_id,
                supplier_code=supplier_code,
                normalized_supplier_code=normalized_code,
                current_cost=cost,
                final_cost=cost,
                currency='ARS',
                status='review' if product.id in ambiguous_product_ids else 'active',
                is_preferred=True,
                match_confidence=70 if product.id in ambiguous_product_ids else 100,
                match_method='legacy_supplier_ref',
                notes=(
                    'Codigo de proveedor historico ambiguo; requiere revision humana.'
                    if product.id in ambiguous_product_ids
                    else ''
                ),
            )
        )
        if len(pending) >= batch_size:
            flush(pending)
            pending = []
    flush(pending)

    duplicate_reviews = []
    for (supplier_id, normalized_code), product_ids in code_groups.items():
        ordered_ids = sorted(product_ids)
        if len(ordered_ids) < 2:
            continue
        for candidate_id in ordered_ids[1:]:
            duplicate_reviews.append(
                ProductDuplicateReview(
                    primary_product_id=ordered_ids[0],
                    candidate_product_id=candidate_id,
                    reason='supplier_code',
                    confidence=100,
                    evidence={
                        'supplier_id': supplier_id,
                        'normalized_supplier_code': normalized_code,
                        'source': 'legacy_attributes_backfill',
                    },
                    status='pending',
                )
            )
    ProductDuplicateReview.objects.using(database).bulk_create(
        duplicate_reviews,
        batch_size=batch_size,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_brandrubro_badge_color_brandrubro_badge_text_and_more'),
        ('core', '0028_adminauditlog_company_admincapabilityprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=100, verbose_name='Codigo proveedor')),
                ('normalized_supplier_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('supplier_description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion del proveedor')),
                ('current_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo actual')),
                ('currency', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dolar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('discount_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento %')),
                ('bonus_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Bonificacion %')),
                ('tax_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Impuesto %')),
                ('final_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo final')),
                ('minimum_purchase_quantity', models.PositiveIntegerField(default=1, verbose_name='Compra minima')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Demora en dias')),
                ('price_list_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lista')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Archivo origen')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fila origen')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('review', 'Revisar'), ('inactive', 'Inactivo')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('is_preferred', models.BooleanField(db_index=True, default=False, verbose_name='Preferido')),
                ('match_confidence', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Confianza de coincidencia')),
                ('match_method', models.CharField(blank=True, max_length=50, verbose_name='Metodo de coincidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='catalog.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor de producto',
                'verbose_name_plural': 'Proveedores de productos',
                'ordering': ['product_id', '-is_preferred', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo anterior')),
                ('new_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo nuevo')),
                ('difference_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Diferencia nominal')),
                ('difference_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='Diferencia porcentual')),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('source', models.CharField(default='manual', max_length=50, verbose_name='Origen')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Archivo origen')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fila origen')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_cost_changes', to=settings.AUTH_USER_MODEL)),
                ('import_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_cost_changes', to='core.importexecution')),
                ('product_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_history', to='catalog.productsupplier', verbose_name='Oferta de proveedor')),
            ],
            options={
                'verbose_name': 'Historial de costo de proveedor',
                'verbose_name_plural': 'Historial de costos de proveedores',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDuplicateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('normalized_sku', 'SKU normalizado'), ('normalized_name', 'Nombre normalizado'), ('supplier_code', 'Codigo de proveedor')], max_length=30)),
                ('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('not_duplicate', 'No son duplicados'), ('confirmed_duplicate', 'Duplicado confirmado')], db_index=True, default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reviews_as_candidate', to='catalog.product')),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reviews_as_primary', to='catalog.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_duplicate_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revision de producto duplicado',
                'verbose_name_plural': 'Revisiones de productos duplicados',
                'ordering': ['status', '-confidence', 'created_at'],
                'indexes': [models.Index(fields=['status', 'confidence'], name='catalog_pro_status_6e8ece_idx'), models.Index(fields=['primary_product', 'candidate_product'], name='catalog_pro_primary_fc5356_idx')],
                'constraints': [models.UniqueConstraint(fields=('primary_product', 'candidate_product', 'reason'), name='uniq_product_duplicate_review_reason'), models.CheckConstraint(condition=models.Q(('primary_product', models.F('candidate_product')), _negated=True), name='duplicate_review_distinct_products')],
            },
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['supplier', 'status'], name='catalog_pro_supplie_dd17c9_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['product', 'status'], name='catalog_pro_product_f8cc38_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['supplier_code'], name='catalog_pro_supplie_a2ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['updated_at'], name='catalog_pro_updated_e47afc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='uniq_product_supplier_offer'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_supplier_code', ''), _negated=True), fields=('supplier', 'normalized_supplier_code'), name='uniq_supplier_external_product_code'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('product',), name='uniq_preferred_supplier_per_product'),
        ),
        migrations.AddIndex(
            model_name='suppliercosthistory',
            index=models.Index(fields=['product_supplier', 'created_at'], name='catalog_sup_product_37fa94_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercosthistory',
            index=models.Index(fields=['source', 'created_at'], name='catalog_sup_source_e1cfdd_idx'),
        ),
        migrations.RunPython(
            backfill_preferred_supplier_offers,
            migrations.RunPython.noop,
        ),
    ]
