# Generated by Django 5.2.10 on 2026-07-14 12:01

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_productsupplier_suppliercosthistory_and_more'),
        ('core', '0028_adminauditlog_company_admincapabilityprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('sheet_name', models.CharField(blank=True, max_length=120, verbose_name='Hoja')),
                ('header_row', models.PositiveIntegerField(default=1, verbose_name='Fila de encabezado')),
                ('column_mapping', models.JSONField(default=dict, verbose_name='Mapeo de columnas')),
                ('default_currency', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dolar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3, verbose_name='Moneda predeterminada')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_import_profiles', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_profiles', to='catalog.supplier', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_import_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de importacion de proveedor',
                'verbose_name_plural': 'Perfiles de importacion de proveedores',
                'ordering': ['supplier__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceListBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(max_length=300, upload_to=catalog.models.supplier_price_list_upload_path, verbose_name='Archivo original')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sheet_name', models.CharField(blank=True, max_length=120)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('default_currency', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dolar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('previewed', 'Previsualizado'), ('applied', 'Aplicado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='uploaded', max_length=20)),
                ('preview_signature', models.CharField(blank=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_supplier_price_list_batches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_price_list_batches', to='core.company', verbose_name='Empresa de carga')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_price_list_batches', to=settings.AUTH_USER_MODEL)),
                ('import_execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_list_batch', to='core.importexecution')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='catalog.supplierimportprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_batches', to='catalog.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lista de precios de proveedor',
                'verbose_name_plural': 'Listas de precios de proveedores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_type', models.CharField(choices=[('source', 'Fila de archivo'), ('absent', 'Ausente en lista')], default='source', max_length=12)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('supplier_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('supplier_description', models.CharField(blank=True, max_length=255)),
                ('match_method', models.CharField(blank=True, max_length=50)),
                ('match_confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('change_type', models.CharField(choices=[('invalid', 'Invalido'), ('unmatched', 'Sin identificar'), ('review', 'Requiere revision'), ('unchanged', 'Sin cambios'), ('increase', 'Aumento'), ('decrease', 'Disminucion'), ('new_relation', 'Nueva relacion'), ('absent', 'No aparece en lista')], db_index=True, max_length=20)),
                ('previous_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('proposed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('proposed_final_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('difference_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('discount_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('bonus_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('tax_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('is_available', models.BooleanField(default=True)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('price_list_date', models.DateField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('apply', 'Aplicar'), ('skip', 'Omitir'), ('review', 'Revisar')], db_index=True, default='skip', max_length=12)),
                ('applied', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.supplierpricelistbatch')),
                ('cost_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_list_rows', to='catalog.suppliercosthistory')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_list_rows', to='catalog.product')),
                ('product_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_rows', to='catalog.productsupplier')),
            ],
            options={
                'verbose_name': 'Fila de lista de proveedor',
                'verbose_name_plural': 'Filas de listas de proveedores',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierimportprofile',
            constraint=models.UniqueConstraint(fields=('supplier', 'name'), name='uniq_supplier_import_profile_name'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelistbatch',
            index=models.Index(fields=['supplier', 'status', 'created_at'], name='catalog_sup_supplie_0cb8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelistbatch',
            index=models.Index(fields=['company', 'created_at'], name='catalog_sup_company_bb86eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpricelistbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('supplier', 'file_sha256'), name='uniq_applied_supplier_file_hash'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelistrow',
            index=models.Index(fields=['batch', 'change_type'], name='catalog_sup_batch_i_431eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelistrow',
            index=models.Index(fields=['batch', 'decision'], name='catalog_sup_batch_i_329679_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelistrow',
            index=models.Index(fields=['matched_product', 'batch'], name='catalog_sup_matched_61cb01_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpricelistrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_supplier_batch_row_number'),
        ),
    ]
