# Generated by Django 5.2.10 on 2026-07-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_supplierimportprofile_supplierpricelistbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercosthistory',
            name='product_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='catalog.productsupplier', verbose_name='Oferta de proveedor'),
        ),
    ]
