# Generated by Django 5.2.10 on 2026-07-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_suppliercosthistory_product_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricelistbatch',
            name='pricing_mode',
            field=models.CharField(choices=[('cost_only', 'Actualizar solo costo'), ('preserve_margin', 'Mantener margen y recalcular venta')], default='cost_only', max_length=24),
        ),
        migrations.AddField(
            model_name='supplierpricelistbatch',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpricelistbatch',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_supplier_price_list_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierpricelistbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('previewed', 'Previsualizado'), ('applied', 'Aplicado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('rolled_back', 'Revertido'), ('rollback_partial', 'Reversion parcial')], db_index=True, default='uploaded', max_length=20),
        ),
    ]
