# Generated by Django 5.2.10 on 2026-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_product_iva_rate_product_tracks_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Permite continuar la operacion cuando el producto controlado no tiene existencia suficiente.', verbose_name='Permitir stock negativo'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Reserva la disponibilidad del producto para futuros flujos de compras.', verbose_name='Disponible para compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Controla si el producto puede agregarse a nuevas operaciones comerciales.', verbose_name='Disponible para venta'),
        ),
    ]
