# Generated by Codex on 2026-07-27

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0029_product_allow_negative_stock_product_is_purchasable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=120, verbose_name="Alias")),
                ("normalized_value", models.CharField(db_index=True, editable=False, max_length=120, unique=True, verbose_name="Alias normalizado")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="catalog.brand", verbose_name="Marca")),
            ],
            options={
                "verbose_name": "Alias de marca",
                "verbose_name_plural": "Alias de marcas",
                "ordering": ["brand__name", "value"],
            },
        ),
        migrations.CreateModel(
            name="BrandCatalogRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_field", models.CharField(choices=[("any", "Cualquier dato"), ("name", "Nombre"), ("sku", "SKU"), ("supplier", "Proveedor"), ("category", "Categoria")], default="any", max_length=20, verbose_name="Campo a revisar")),
                ("match_mode", models.CharField(choices=[("contains", "Contiene"), ("word", "Palabra completa"), ("prefix", "Comienza con")], default="word", max_length=20, verbose_name="Tipo de coincidencia")),
                ("pattern", models.CharField(max_length=160, verbose_name="Texto a reconocer")),
                ("priority", models.PositiveSmallIntegerField(default=50, verbose_name="Prioridad")),
                ("confidence", models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="Confianza")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="catalog_rules", to="catalog.brand", verbose_name="Marca")),
                ("brand_rubro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="catalog_rules", to="catalog.brandrubro", verbose_name="Rubro")),
                ("brand_subrubro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="catalog_rules", to="catalog.brandsubrubro", verbose_name="Subrubro")),
            ],
            options={
                "verbose_name": "Regla de catalogacion por marca",
                "verbose_name_plural": "Reglas de catalogacion por marca",
                "ordering": ["-priority", "-confidence", "brand__name", "pattern"],
            },
        ),
        migrations.CreateModel(
            name="BrandCatalogBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(choices=[("assign", "Asignacion manual"), ("rule", "Asignacion sugerida"), ("import", "Importacion")], default="assign", max_length=20, verbose_name="Origen")),
                ("status", models.CharField(choices=[("applied", "Aplicado"), ("undone", "Deshecho")], db_index=True, default="applied", max_length=20, verbose_name="Estado")),
                ("product_ids", models.JSONField(blank=True, default=list, verbose_name="Productos")),
                ("created_rubro_row_ids", models.JSONField(blank=True, default=list)),
                ("created_subrubro_row_ids", models.JSONField(blank=True, default=list)),
                ("observation", models.TextField(verbose_name="Observacion")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="catalog_batches", to="catalog.brand", verbose_name="Marca")),
                ("brand_rubro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="catalog_batches", to="catalog.brandrubro", verbose_name="Rubro")),
                ("brand_subrubro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="catalog_batches", to="catalog.brandsubrubro", verbose_name="Subrubro")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="brand_catalog_batches", to=settings.AUTH_USER_MODEL, verbose_name="Creado por")),
                ("undone_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="undone_brand_catalog_batches", to=settings.AUTH_USER_MODEL, verbose_name="Deshecho por")),
            ],
            options={
                "verbose_name": "Lote de catalogacion por marca",
                "verbose_name_plural": "Lotes de catalogacion por marca",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
