# Generated by Codex on 2026-08-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0031_brandcatalogbatch_reversible_removals"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBrandMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("include_descendants", models.BooleanField(default=True, verbose_name="Incluir subcategorias")),
                ("status", models.CharField(choices=[("confirmed", "Confirmado"), ("rejected", "Descartado")], db_index=True, default="confirmed", max_length=20, verbose_name="Estado")),
                ("observation", models.CharField(max_length=300, verbose_name="Observacion")),
                ("last_applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="category_mappings", to="catalog.brand", verbose_name="Marca")),
                ("brand_rubro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="category_mappings", to="catalog.brandrubro", verbose_name="Rubro de destino")),
                ("brand_subrubro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="category_mappings", to="catalog.brandsubrubro", verbose_name="Subrubro de destino")),
                ("canonical_category", models.ForeignKey(blank=True, help_text="Categoria de familia que quedara como referencia cuando se retire la rama heredada de marca.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="legacy_brand_mappings", to="catalog.category", verbose_name="Familia canonica")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_category_brand_mappings", to=settings.AUTH_USER_MODEL)),
                ("last_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="category_mappings", to="catalog.brandcatalogbatch", verbose_name="Ultimo lote aplicado")),
                ("source_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="brand_mappings", to="catalog.category", verbose_name="Categoria de origen")),
            ],
            options={
                "verbose_name": "Vinculo entre categoria y marca",
                "verbose_name_plural": "Vinculos entre categorias y marcas",
                "ordering": ["source_category__name", "brand__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="categorybrandmapping",
            constraint=models.UniqueConstraint(fields=("source_category",), name="uniq_source_category_brand_bridge"),
        ),
    ]
