# Generated by Django 5.2.10 on 2026-09-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_categorybrandmapping_optional_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Es portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['product', 'order'], name='catalog_pro_product_631828_idx'), models.Index(fields=['product', 'is_primary'], name='catalog_pro_product_c9ec4d_idx')],
            },
        ),
    ]
