# Generated by Django 5.2.10 on 2026-02-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_clientfavoriteproduct_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='converted_order',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteItem',
        ),
    ]
