# Generated by Django 5.2.10 on 2026-02-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_invoiceitem_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClampQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('dollar_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Dolar')),
                ('steel_price_usd', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio acero USD')),
                ('supplier_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desc. proveedor (%)')),
                ('general_increase_pct', models.DecimalField(decimal_places=2, default=23, max_digits=6, verbose_name='Aumento general (%)')),
                ('clamp_type', models.CharField(choices=[('trefilada', 'Trefilada'), ('laminada', 'Laminada')], max_length=20, verbose_name='Tipo abrazadera')),
                ('is_zincated', models.BooleanField(default=False, verbose_name='Zincado')),
                ('diameter', models.CharField(max_length=20, verbose_name='Diametro')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Ancho (mm)')),
                ('length_mm', models.PositiveIntegerField(verbose_name='Largo (mm)')),
                ('profile_type', models.CharField(choices=[('PLANA', 'PLANA'), ('SEMICURVA', 'SEMICURVA'), ('CURVA', 'CURVA')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo base')),
                ('price_list', models.CharField(choices=[('lista_1', 'Lista 1'), ('lista_2', 'Lista 2'), ('lista_3', 'Lista 3'), ('lista_4', 'Lista 4'), ('facturacion', 'Facturacion')], max_length=20, verbose_name='Lista')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio final')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clamp_quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cotizacion de Abrazadera',
                'verbose_name_plural': 'Cotizaciones de Abrazadera',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='orders_clam_created_e18145_idx'), models.Index(fields=['client_name'], name='orders_clam_client__46265e_idx'), models.Index(fields=['price_list'], name='orders_clam_price_l_8c63f8_idx')],
            },
        ),
    ]
