# Generated by Django 5.2.11 on 2026-02-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_clampmeasurerequest_added_to_cart_at_and_more'),
        ('orders', '0004_clampquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='clamp_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.clampmeasurerequest', verbose_name='Solicitud de medida'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='clamp_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.clampmeasurerequest', verbose_name='Solicitud de medida'),
        ),
    ]
