# Generated by Django 5.2.11 on 2026-02-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _get_column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name})")
            return {row[1] for row in cursor.fetchall()}
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
        return {column.name for column in description}


def add_missing_order_columns(apps, schema_editor):
    table_name = "orders_order"
    columns = _get_column_names(schema_editor, table_name)

    vendor = schema_editor.connection.vendor
    statements = {
        "assigned_to_id": (
            "ALTER TABLE orders_order ADD COLUMN assigned_to_id INTEGER NULL"
            if vendor == "sqlite"
            else "ALTER TABLE orders_order ADD COLUMN assigned_to_id bigint NULL"
        ),
        "follow_up_at": "ALTER TABLE orders_order ADD COLUMN follow_up_at datetime NULL",
        "follow_up_done_at": "ALTER TABLE orders_order ADD COLUMN follow_up_done_at datetime NULL",
        "follow_up_note": "ALTER TABLE orders_order ADD COLUMN follow_up_note varchar(255) NOT NULL DEFAULT ''",
        "priority": "ALTER TABLE orders_order ADD COLUMN priority varchar(16) NOT NULL DEFAULT 'normal'",
        "saas_document_cae": "ALTER TABLE orders_order ADD COLUMN saas_document_cae varchar(40) NOT NULL DEFAULT ''",
        "saas_document_date": "ALTER TABLE orders_order ADD COLUMN saas_document_date date NULL",
        "saas_document_number": "ALTER TABLE orders_order ADD COLUMN saas_document_number varchar(60) NOT NULL DEFAULT ''",
        "saas_document_pdf": "ALTER TABLE orders_order ADD COLUMN saas_document_pdf varchar(100) NULL",
        "saas_document_total": (
            "ALTER TABLE orders_order ADD COLUMN saas_document_total decimal NULL"
            if vendor == "sqlite"
            else "ALTER TABLE orders_order ADD COLUMN saas_document_total numeric(12,2) NULL"
        ),
        "saas_document_type": "ALTER TABLE orders_order ADD COLUMN saas_document_type varchar(24) NOT NULL DEFAULT ''",
    }

    for column, sql in statements.items():
        if column in columns:
            continue
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_clamp_request_orderitem_clamp_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_order_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='assigned_to',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='follow_up_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Seguimiento para'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='follow_up_done_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Seguimiento resuelto'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='follow_up_note',
                    field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nota seguimiento'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='priority',
                    field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=16, verbose_name='Prioridad'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_cae',
                    field=models.CharField(blank=True, default='', max_length=40, verbose_name='CAE SaaS'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_date',
                    field=models.DateField(blank=True, null=True, verbose_name='Fecha comprobante SaaS'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_number',
                    field=models.CharField(blank=True, default='', max_length=60, verbose_name='Numero comprobante SaaS'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_pdf',
                    field=models.FileField(blank=True, null=True, upload_to='orders/saas/', verbose_name='PDF comprobante SaaS'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_total',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total comprobante SaaS'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='saas_document_type',
                    field=models.CharField(blank=True, default='', max_length=24, verbose_name='Tipo comprobante SaaS'),
                ),
            ],
        ),
    ]
