# Generated by Django 5.2.10 on 2026-03-09 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clientcompany_clientpayment_company_and_more'),
        ('core', '0007_company_importexecution_company'),
        ('orders', '0007_order_orders_orde_status_25e057_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='clampquotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clamp_quotations', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.clientcompany', verbose_name='Cliente empresa'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'created_at'], name='orders_orde_company_060859_idx'),
        ),
    ]
