# Generated by Django 5.2.11 on 2026-03-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_companies'),
        ('orders', '0008_cart_company_clampquotation_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'company'], name='orders_cart_user_id_eead93_idx'),
        ),
    ]
