# Generated by Django 5.2.11 on 2026-03-09 17:38

from django.db import migrations, models


def add_billing_columns_if_missing(apps, schema_editor):
    table = "orders_order"
    with schema_editor.connection.cursor() as cursor:
        existing = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }

        if "billing_company" not in existing:
            cursor.execute(
                "ALTER TABLE orders_order ADD COLUMN billing_company varchar(20) NOT NULL DEFAULT 'flexs'"
            )
        if "billing_mode" not in existing:
            cursor.execute(
                "ALTER TABLE orders_order ADD COLUMN billing_mode varchar(20) NOT NULL DEFAULT 'official'"
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cart_user_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_billing_columns_if_missing, noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='billing_company',
                    field=models.CharField(default='flexs', max_length=20, verbose_name='Empresa facturacion'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='billing_mode',
                    field=models.CharField(default='official', max_length=20, verbose_name='Modo facturacion'),
                ),
            ],
        ),
    ]
