# Generated by Django 5.2.10 on 2026-03-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('orders', '0010_order_billing_company_order_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percentage_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.pricelist', verbose_name='Lista de precio'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio base unitario'),
        ),
    ]
