# Generated by Django 5.2.10 on 2026-03-19 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ensure_clienttransaction_billing_company_column'),
        ('catalog', '0016_pricelist_pricelistitem_and_more'),
        ('core', '0018_ensure_admincompanyaccess_table'),
        ('orders', '0012_order_external_id_order_external_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='Linea')),
                ('product_sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio base unitario')),
                ('discount_percentage_used', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('price_at_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item de solicitud comercial',
                'verbose_name_plural': 'Items de solicitudes comerciales',
                'ordering': ['order_request_id', 'line_number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='origin_channel',
            field=models.CharField(choices=[('catalog', 'Catalogo'), ('admin', 'Admin'), ('whatsapp', 'WhatsApp'), ('phone', 'Telefono'), ('other', 'Otro')], db_index=True, default='admin', max_length=20, verbose_name='Canal origen'),
        ),
        migrations.CreateModel(
            name='OrderProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Vencida')], db_index=True, default='pending', max_length=16, verbose_name='Estado')),
                ('is_current', models.BooleanField(default=True, verbose_name='Version vigente')),
                ('message_to_client', models.TextField(blank=True, verbose_name='Mensaje al cliente')),
                ('internal_note', models.TextField(blank=True, verbose_name='Nota interna')),
                ('proposed_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('proposed_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('proposed_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto descuento')),
                ('proposed_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado el')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido el')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Vence el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_proposals_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_proposals_responded', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Propuesta comercial',
                'verbose_name_plural': 'Propuestas comerciales',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='orders.orderproposal', verbose_name='Propuesta origen'),
        ),
        migrations.CreateModel(
            name='OrderProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='Linea')),
                ('product_sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio base unitario')),
                ('discount_percentage_used', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('price_at_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('clamp_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_proposal_items', to='catalog.clampmeasurerequest', verbose_name='Solicitud de medida')),
                ('order_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderproposal', verbose_name='Propuesta')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_proposal_items', to='catalog.pricelist', verbose_name='Lista de precio')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_proposal_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de propuesta comercial',
                'verbose_name_plural': 'Items de propuestas comerciales',
                'ordering': ['order_proposal_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('in_review', 'En revision'), ('proposal_sent', 'Propuesta enviada'), ('waiting_client', 'Esperando respuesta del cliente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('converted', 'Convertido a documento')], db_index=True, default='draft', max_length=24, verbose_name='Estado')),
                ('origin_channel', models.CharField(choices=[('catalog', 'Catalogo'), ('admin', 'Admin'), ('whatsapp', 'WhatsApp'), ('phone', 'Telefono'), ('other', 'Otro')], db_index=True, default='catalog', max_length=20, verbose_name='Canal origen')),
                ('client_note', models.TextField(blank=True, verbose_name='Nota del cliente')),
                ('admin_note', models.TextField(blank=True, verbose_name='Nota interna')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo rechazo')),
                ('requested_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('requested_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('requested_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto descuento')),
                ('requested_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tomado en revision el')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Convertido el')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to='accounts.clientcompany', verbose_name='Cliente empresa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='core.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitud comercial',
                'verbose_name_plural': 'Solicitudes comerciales',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='orderproposal',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='orders.orderrequest', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='orders.orderrequest', verbose_name='Solicitud origen'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['origin_channel', 'created_at'], name='orders_orde_origin__f256c9_idx'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='clamp_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request_items', to='catalog.clampmeasurerequest', verbose_name='Solicitud de medida'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderrequest', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request_items', to='catalog.pricelist', verbose_name='Lista de precio'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request_items', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='orderproposalitem',
            index=models.Index(fields=['order_proposal', 'line_number'], name='orders_orde_order_p_071850_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderproposalitem',
            unique_together={('order_proposal', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['company', 'status', 'created_at'], name='orders_orde_company_a0da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='orders_orde_user_id_54e4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['origin_channel', 'created_at'], name='orders_orde_origin__0d4ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproposal',
            index=models.Index(fields=['order_request', 'status', 'created_at'], name='orders_orde_order_r_d5cac8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproposal',
            index=models.Index(fields=['order_request', 'is_current'], name='orders_orde_order_r_424d7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderproposal',
            unique_together={('order_request', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='orderrequestitem',
            index=models.Index(fields=['order_request', 'line_number'], name='orders_orde_order_r_fa1865_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrequestitem',
            unique_together={('order_request', 'line_number')},
        ),
    ]
