# Generated by Django 5.2.10 on 2026-03-19 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderrequestitem_order_origin_channel_orderproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Solicitud creada'), ('review_started', 'Revision iniciada'), ('proposal_sent', 'Propuesta enviada'), ('proposal_accepted', 'Propuesta aceptada'), ('proposal_rejected', 'Propuesta rechazada'), ('confirmed', 'Solicitud confirmada'), ('rejected', 'Solicitud rechazada'), ('converted', 'Solicitud convertida'), ('quote_generated', 'Cotizacion generada'), ('invoice_generated', 'Factura generada')], db_index=True, max_length=32, verbose_name='Evento')),
                ('from_status', models.CharField(blank=True, max_length=24, verbose_name='Estado anterior')),
                ('to_status', models.CharField(blank=True, max_length=24, verbose_name='Estado nuevo')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Evento de solicitud comercial',
                'verbose_name_plural': 'Eventos de solicitudes comerciales',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order_request', 'created_at'], name='orders_orde_order_r_381c50_idx'), models.Index(fields=['event_type', 'created_at'], name='orders_orde_event_t_1836b4_idx')],
            },
        ),
    ]
