# Generated by Django 5.2.11 on 2026-07-13 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_clienttransaction_movement_state'),
        ('core', '0028_adminauditlog_company_admincapabilityprofile_and_more'),
        ('orders', '0014_orderrequestevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Clave de idempotencia'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('source_request__isnull', False)), fields=('source_request',), name='unique_order_per_source_request'),
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'user', 'idempotency_key'), name='unique_order_request_idempotency_key'),
        ),
    ]
